### ISSUE TITLE
RateLimitAutoConfiguration$Bucket4jJCacheConfiguration

### ISSUE THREAD

**Issue by howtoinstall** [marcosbarbero/spring-cloud-zuul-ratelimit#102]
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method jCache4jHazelcastRateLimiter in com.marcosbarbero.cloud.autoconfigure.zuul.ratelimit.RateLimitAutoConfiguration$Bucket4jJCacheConfiguration required a bean of type 'javax.cache.Cache' that could not be found.

Action:

Consider defining a bean of type 'javax.cache.Cache' in your configuration.

**Comment by lchayoun** [comment]
If you are using jcache you need to provide the cache bean
