### ISSUE TITLE
Properties creating error while converting .yml to .properties file

### ISSUE THREAD

**Issue by mona2702** [marcosbarbero/spring-cloud-zuul-ratelimit#104]
Hi Team,

While converting yml properties to application.properties . 
I am mentioning the policy list as my service name for eg : TestArtifact. 
But while building its showing error that policy list attribute is not convertible to map from string. 

Can you help with the above error. 

Thanks in advance.

**Comment by mona2702** [comment]
zuul.ratelimit.key-prefix=${spring.application.name}
zuul.ratelimit.enabled=true
zuul.ratelimit.behind-proxy= true
zuul.ratelimit.policy-list=MyArtifactName
zuul.ratelimit.policy-list.MyArtifactName.limit= 4
zuul.ratelimit.policy-list.MyArtifactName.quota=100
zuul.ratelimit.policy-list.MyArtifactName.refresh-interval= 60
zuul.ratelimit.policy-list.MyArtifactName.type=url

**Comment by marcosbarbero** [comment]
I think this should work

```
zuul.ratelimit.key-prefix=${spring.application.name}
zuul.ratelimit.enabled=true
zuul.ratelimit.behind-proxy=true
zuul.ratelimit.policy-list.MyArtifactName[0].limit=4
zuul.ratelimit.policy-list.MyArtifactName[0].quota=100
zuul.ratelimit.policy-list.MyArtifactName[0].refresh-interval= 60
zuul.ratelimit.policy-list.MyArtifactName[0].type=url
```

**Comment by mona2702** [comment]
Its working now. Thanks. 
Just one more thing. So , if i want to add more artifacts to the network policy with same configuration then is there a way to mention all the artifacts at a time or do we need to mention individual policies for artifact.
For Eg : I have MyArtifact1, MyArtifact2 and i want to add rate limiting to both. 

So, 
zuul.ratelimit.key-prefix=${spring.application.name}
zuul.ratelimit.enabled=true
zuul.ratelimit.behind-proxy=true
zuul.ratelimit.policy-list.MyArtifact1[0].limit=4
zuul.ratelimit.policy-list.MyArtifact1[0].quota=100
zuul.ratelimit.policy-list.MyArtifact1[0].refresh-interval= 60
zuul.ratelimit.policy-list.MyArtifact1[0].type=url

zuul.ratelimit.policy-list.MyArtifact2[0].limit=4
zuul.ratelimit.policy-list.MyArtifact2[0].quota=100
zuul.ratelimit.policy-list.MyArtifact2[0].refresh-interval= 60
zuul.ratelimit.policy-list.MyArtifact2[0].type=url

or can is there a way to club the two configuration .
Also, If the type url only applies to api url of the artifact .right???

**Comment by marcosbarbero** [comment]
You can create a `default-policy-list` in which will be applied to all the services.

**Comment by islowcity** [comment]
Good answer.

**Comment by zackzhangzz** [comment]
- type: #optional value for each type
            - user=anonymous
            - origin=somemachine.com
            - url=/api #url prefix
            - role=user
            - httpmethod=get #case insensitive

how  convert .yml to .properties ?

**Comment by marcosbarbero** [comment]
I think you can refer to [this reply](https://github.com/marcosbarbero/spring-cloud-zuul-ratelimit/issues/104#issuecomment-416188108)
