### ISSUE TITLE
Remove InMemory implementation

### ISSUE THREAD

**Issue by lchayoun** [marcosbarbero/spring-cloud-zuul-ratelimit#112]
Since we support bucket4j, and it has in memory caches support, out InMemory implementation is not necessary and it is also dangerous since it can't be limited in size

**Comment by lchayoun** [comment]
@marcosbarbero WDYT?

**Comment by marcosbarbero** [comment]
Sounds reasonable, let's do that.

**Comment by mattwmj** [comment]
Can you give me some guide or example on config bucket4j  in memory caches?
