### ISSUE TITLE
why there need quota limit?

### ISSUE THREAD

**Issue by dchack** [marcosbarbero/spring-cloud-zuul-ratelimit#114]
Hi, I can't  think out why there need quota limit.
Can you give me some scene for it？

**Comment by lchayoun** [comment]
Hi @dchack, sometimes requests are not equal and the resources they consume and it is only known at the end if the request. 
So, let's say the user can create a request that range from 10 seconds to 1 second to provide, so limit by the number of requests is not enough. Using quota we can limit the user to 5 seconds for example so everybody get their fair share.
