### ISSUE TITLE
Rate limiting based on user's role

### ISSUE THREAD

**Issue by emeve89** [marcosbarbero/spring-cloud-zuul-ratelimit#126]
Hello everyone,

I'm trying to set up a rate limit policy in my application. The thing is that I need to limit the number of requests to a given service based on the role of a user. 

Quick example:
- Anonymous users (without an account) => 10  requests per minute.
- Normal users => 50 requests per minute.
- Premium users => 100 requests per minute.
- Admin users => No restriction.

How should I set up my application.yml file to fulfill these constraints.

Thank you in advance!

**Comment by marcosbarbero** [comment]
Duplicates #127
