### ISSUE TITLE
Restrict number of request based on user' role

### ISSUE THREAD

**Issue by emeve89** [marcosbarbero/spring-cloud-zuul-ratelimit#127]
Hello everyone,

I'm trying to set up a rate limit policy in my application. The thing is that I need to limit the request number to a given service based on the role of the user. 

Quick example:
- Anonymous users => 10  requests per minute.
- Normal users => 50 requests per minute.
- Premium users => 100 requests per minute.
- Admin users => No restriction.

How should I set up my application.yml file to fulfill these constraints.

Thank you in advance!

**Comment by marcosbarbero** [comment]
Hi @emeve89 currently we don't support rate limiting based on the user's role.

Hey @lchayoun what do you think about this feature? I kinda liked it.

**Comment by lchayoun** [comment]
Sounds really good!

**Comment by marcosbarbero** [comment]
Hi @emeve89 [v2.2.1.RELEASE](https://github.com/marcosbarbero/spring-cloud-zuul-ratelimit/releases/tag/v2.2.1.RELEASE) adds this feature, it was pushed to the maven central and may be available in the next few hours.

If you find any issue let me know.
