### ISSUE TITLE
I have a suggest

### ISSUE THREAD

**Issue by lixinglin0213** [marcosbarbero/spring-cloud-zuul-ratelimit#133]
The gateway is highly available. We need to dynamically modify the policy information when the gateway is started. Can we provide some interfaces for redis storage to provide additional interfaces for adding, deleting, and modifying operations?

**Comment by marcosbarbero** [comment]
Hi @lixinglin0213 I'm not quite sure about what you mean.

The supported configuration is the same as any `spring boot` / `spring cloud` application, if you actually talking about manipulating the storage itself then you should rely on the chosen storage UI instead such as `redis-cli` for Redis.
