### ISSUE TITLE
[FEATURE] Rate limit by Http method

### ISSUE THREAD

**Issue by XieEDeHeiShou** [marcosbarbero/spring-cloud-zuul-ratelimit#135]
For exsample:
```java
@RestController
@RequestMapping("/test")
public class Controller {
    @PostMapping
    public void post(){}
    @GetMapping
    public void get(){}
}
```
When `RateLimitType` set to `ORIGN,URL`, `limit` set to 10, then the user is unable to call 10 `POST /test` and 10 `GET /test` in a window.

**Comment by marcosbarbero** [comment]
I just pushed the release [v2.2.2.RELEASE](https://github.com/marcosbarbero/spring-cloud-zuul-ratelimit/releases/tag/v2.2.2.RELEASE) to the maven central, it will be available today.
