### ISSUE TITLE
Default policy configuration

### ISSUE THREAD

**Issue by lchayoun** [marcosbarbero/spring-cloud-zuul-ratelimit#14]
Currently each service need to be configured in order to use rate limit
Since routes can be auto discovered in the gateway I think it will be a good idea to add a default policy configuration that can be overridden by each service

@marcosbarbero WDYT?

**Comment by marcosbarbero** [comment]
Not sure if it's good to have a default policy,  auto discovery all the services and apply it.

Let's say you have a hundred services and only five of them need to have a rate limit configured. If we apply a default policy it will apply for everything even for those that doesn't need it.

WDYT?

**Comment by lchayoun** [comment]
Maybe add a way to configure default policy, keeping the current behavior if such not configured?

I think that it is important to all services, even setting a default high limit.
But currently there is no way to configure default which make it hard to maintain the gateway

**Comment by marcosbarbero** [comment]
@lchayoun [v1.3.1.RELEASE](https://github.com/marcosbarbero/spring-cloud-zuul-ratelimit/releases/tag/v1.3.1.RELEASE) available on maven central, if you find any issue let me know.
