### ISSUE TITLE
Rate limit by client-id

### ISSUE THREAD

**Issue by marcosbarbero** [marcosbarbero/spring-cloud-zuul-ratelimit#145]
Recently a developer talked to me about adding rate limiting not only by the username but also by `OAuth2` `clientId`.

WDYT @lchayoun?

**Comment by keisersoze** [comment]
Hi Marcos, It would be a very nice feature to have. I think it's the only important option that your library is missing. Thank you for the work you have done.

**Comment by lchayoun** [comment]
I'm not familiar with the `OAuth2` mechanism.
What will the `request.getRemoteUser()` method return when using `OAuth2`?

**Comment by marcosbarbero** [comment]
OAuth2 works with few grant types, all of them requires a `clientId` but not all of them requires an actual `user`, given that the `request.getRemoteUser()` only returns the `clientId` when the grant type used is `client_credentials`, every other grant type will be returning the authenticated user.

Due to that particularity of OAuth2 authentication object, I do believe it would be good to add the `clientId` as an option to the lib.

**Comment by marcosbarbero** [comment]
Thanks for the feedback @keisersoze :)
