### ISSUE TITLE
A request for an endpoint with 429 response is being counted for the service limit 

### ISSUE THREAD

**Issue by glokeshathena** [marcosbarbero/spring-cloud-zuul-ratelimit#152]
**Configuration:**

Below is the rate limiting configuration for a service named "test-app", I have defined 3 configurations:

1. Service level limit, 5 req for every 10sec
2. Limit for a GET endpoint '/api/', 3 req for every 10sec
3. Limit for a POST endpoint '/api/', 2 req for every 10sec

ratelimit:
    enabled: true
    repository: REDIS
    policy-list:
      test-app:

      - limit: 5
        refresh-interval: 10

      - limit: 3
        refresh-interval: 10
        type:
        - origin
        - url=/api/
        - httpmethod=post

      - limit: 2
        refresh-interval: 10
        type:
        - origin
        - url=/api/
        - httpmethod=get

**Observation:**

When I hit 5 GET /api/ requests, I get 3 200 and 2 429 as expected, but the 429 response is also considered for the service limit, so when I hit POST /api/, I get 429 which doesn't seem right.

**Comment by glokeshathena** [comment]
@marcosbarbero, could you pls review this issue and let us know if you plan to fix this?

**Comment by marcosbarbero** [comment]
Hi @glokeshathena, I forgot to update you here. I'm already working on that and writing tests to fix it, so far I'm still failing but I'm doing my best to get it fixed before Friday.

**Comment by glokeshathena** [comment]
@marcosbarbero any update on this?

**Comment by marcosbarbero** [comment]
Sorry, @glokeshathena I'm abroad and I didn't have that much time to look into it if you have any working fix please submit a PR and I'll review it asap.

**Comment by vasilaio** [comment]
Hi @glokeshathena, according to your configuration, you defined:
1. a max of 5 requests to the "api" endpoint (disregard of the http method)
2. a max of 3 POST requests to the "api" endpoint
3. a max of 2 GET requests  to the "api" endpoint
When you made 5 GET /api requests, then both policies (1 and 2) where started, after second request you should get the 429 response. The policy for "POST" request didn't applied. 
In your case, the 429 response is not triggered by POST policy (3) but the global one (1).
You can check the #274 test.
