### ISSUE TITLE
Unable to find parent artefact 'spring-cloud-zuul-ratelimit-parent'

### ISSUE THREAD

**Issue by samyakmehta** [marcosbarbero/spring-cloud-zuul-ratelimit#16]
I am trying to add this dependency in my project.

On build, maven tries to fetch the url - https://jcenter.bintray.com/com/marcosbarbero/cloud/spring-cloud-zuul-ratelimit-parent/1.3.0.RELEASE/spring-cloud-zuul-ratelimit-parent-1.3.0.RELEASE.pom

And I get an error - 
Failed to execute goal on project gateway-service: Could not resolve dependencies for project io.cimpress.abc.backbone.gateway:gateway-service:jar:1.0.0: Failed to collect dependencies at com.marcosbarbero.cloud:spring-cloud-zuul-ratelimit:jar:1.3.0.RELEASE: Failed to read artifact descriptor for com.marcosbarbero.cloud:spring-cloud-zuul-ratelimit:jar:1.3.0.RELEASE: Could not find artifact com.marcosbarbero.cloud:spring-cloud-zuul-ratelimit-parent:pom:1.3.0.RELEASE in central

On checking the file, spring-cloud-zuul-ratelimit/spring-cloud-zuul-ratelimit-core/pom.xml
I found that the parent artefact id is 'spring-cloud-zuul-ratelimit-parent' which I could not find in maven artefactory. I am not sure if this is the reason that I am not able to add dependency.

Can someone help me with this?
Thanks

**Comment by marcosbarbero** [comment]
That's for sure an issue.
I'll try to fix it shortly, I'm sorry for the inconvenience.

**Comment by marcosbarbero** [comment]
@samyakmehta I just pushed the missing dependencies to maven central. I believe everything will be fine in the next coming 20min. Let me know if you find any issue.

**Comment by samyakmehta** [comment]
@marcosbarbero I'm sorry for the late reply.
I just tested, it works fine now!

**Comment by marcosbarbero** [comment]
Great! Thanks for the heads up.
If you find anything else just let me know.
