### ISSUE TITLE
Is it possible to whitelist certain IP addresses?

### ISSUE THREAD

**Issue by andrew-holman** [marcosbarbero/spring-cloud-zuul-ratelimit#160]
I have already implemented the rate limiting in my project. However, I have a specific IP address that will be making many requests and I don't want to limit it from making calls. Ideally I would like to be able to input a list of IP addresses that don't get rate limited. Is this at all possible currently? I am using Consul repository if that matters at all.

**Comment by marcosbarbero** [comment]
Hi @andrew-holman sorry for the delay.
In the current implementation, it's not possible to whitelist an IP. What you could do is to create a policy with a really high value for its limit.

**Comment by andrew-holman** [comment]
Hi Marcos, so I'm trying to implement that but my issue is that I set the origin to be a certain IP address and give that a really high limit. Then I set the second limit with just an empty origin because I want all other IP addresses to be caught. However, when I make a request using the designated IP address the ratelimiting appears to be called twice, once for the special case with a limit of 15 and again for the general case with a limit of 5. So the limit with 5 is reached first and then says that the limit has been reached for it. Is there a way I can work around this? The code I'm testing it with looks like this:
`    policy-list:
      sample-policy:
        - limit: 15
          refresh-interval: 20
          type:
            - origin=127.0.0.1
        - limit: 5
          refresh-interval: 20
          type:
            - origin`

**Comment by marcosbarbero** [comment]
I was expecting the more specific one to have priority here, tbh it sounds like a bug to me 😢

**Comment by andrew-holman** [comment]
So I had a look to try and fix this and I may have found a solution. Essentially I check if a limit has already been found when it is checking whether or not to apply the limits. However, this does not take the most specific limit, because I don't know how to define what is the most complex. Instead it simply takes the first limit to succeed. I forked the repo and made these changes. It passed all the tests and seems to work from what I can see. Does this look like a reasonable solution to you?

https://github.com/andrew-holman/spring-cloud-zuul-ratelimit/commit/1d063f900f97daa227f8a538812ad36b8099b91f#diff-97b509481a0b7c92dffaef2827b90896

**Comment by lchayoun** [comment]
@marcosbarbero I don't think it's a bug, several policies are needed in order to enforce certain limit per user but a different limit per origin and a lower limit per user+host.
But, I think this use case is valid and we need to support it in a different way.
We can an option on a policy (breakOnMatch:true|false) which will not evaluate the following policies in the list if it matches the request.

**Comment by andrew-holman** [comment]
That makes sense, I went in and made those changes so now it can be enabled by setting breakOnMatch to true. It is also default false so this shouldn't affect any current projects without the breakOnMatch tag.

https://github.com/marcosbarbero/spring-cloud-zuul-ratelimit/commit/fd01e4a94db8ced41b856fdcbbbf4db1ddb32024

**Comment by marcosbarbero** [comment]
@lchayoun I probably misplaced `bug` here hehehe what I meant was I thought somehow that was already the expected behavior (the one you suggested).
