### ISSUE TITLE
Redis vulnerability with key expiration not being set

### ISSUE THREAD

**Issue by alowrey** [marcosbarbero/spring-cloud-zuul-ratelimit#162]
I ran into a vulnerability with the RedisRateLimiter class in regards to how it manages key expiration. In `calcRemaining` there's the following code block:

```
current = redisTemplate.opsForValue().increment(key, usage);
// Redis returns the value of key after the increment, check for the first increment, and the expiration time is set
if (current != null && current.equals(usage)) {
    handleExpiration(key, refreshInterval);
}
```

If `increment()` succeeds on a new entry and `handleExpiration()` fails for whatever reason, then the entry won't have an expiration, and no subsequent call into `calcRemaining` will attempt to set it since `current.equals(usage)` will be false. In which case the remaining limit will never reset, so once the limit number of calls is made, 429 will always be returned for the given key. The only way to fix it is to manually remove the key from redis. Obviously this is a major issue, since the filter will discard valid requests incorrectly.

A fix to this issue could look something like this:

```
boolean success = redisTemplate.opsForValue().setIfAbsent(key, usage, refreshInterval);
if(!success)
{
   // Key already exists, increment
  redisTemplate.opsForValue().increment(key, usage);
} 
```

That way you're guaranteed every entry added to redis has its expiration properly set. It's an extra call to Redis, but in this case seems necessary.

**Comment by alowrey** [comment]
Note this race condition is discussed in the Redis docs for INCR: https://redis.io/commands/INCR#pattern-rate-limiter-2

**Comment by marcosbarbero** [comment]
Hi @alowrey thank you very much for your finding. I am traveling at this moment and I won't have time to fix it in the next few days if you have any spare time I would be really thankful if you could open a PR fixing it so I can push a new version to maven central right away.

**Comment by alowrey** [comment]
Hi @marcosbarbero, thanks for the response. I'll try to take a stab at it sometime this week.
