### ISSUE TITLE
How to tier policies and use a different policy Type?

### ISSUE THREAD

**Issue by vshah1975** [marcosbarbero/spring-cloud-zuul-ratelimit#163]
Hi Marcos,

I have a use case where I am trying to rate limit based on an element in the request object (private key) and then tier it with a corresponding URL. For example: 
key1 has 5 req/sec to URL=/service/operationA, 
key1 has 10 req/sec to all other URLs for /service/**
key2 has 2 req/sec to URL=/service/operationA. 
key2 has 6 req/sec to all other URLs=/service/**. 
All other keys have unlimited access to URL=/service/**

Now this is not of type "user" since user goes after the request.getRemoteUser(). In my case, I need to look at the request.getBody to get the REST message and retrieve the key from there. (as I cannot look at the bearer oauth2 token to get the key from that). How do you recommend I approach this configuration extension.

I dont mind writing any extensions as necessary, but just need some direction.

Thanks,
Viral Shah

**Comment by marcosbarbero** [comment]
Hi @vshah1975 sorry for the huge delay.
Just for me to understand, would it be possible for you just to get the username from a JWT token?

**Comment by vshah1975** [comment]
Sorry for the delay, but we had figured out an extension to the RateLimitUtil and overridden the getUser method based on the requestType coming from the props and able to achieve without any additional work to the core library.
