### ISSUE TITLE
Question ---- why we need this if zuul already supports this.

### ISSUE THREAD

**Issue by surapuramakhil** [marcosbarbero/spring-cloud-zuul-ratelimit#178]
I have gone through read me of this repo. what-ever it says is the same present in zuul.
so I couldn't identify what is the use of this

**Comment by marcosbarbero** [comment]
HI @surapuramakhil even on Zuul 2 Rate Limit is yet to be supported, you can read more here https://github.com/Netflix/zuul/wiki/Coming-Soon
