### ISSUE TITLE
How to load zuul configs from db instead of yml file?

### ISSUE THREAD

**Issue by denghuichao** [marcosbarbero/spring-cloud-zuul-ratelimit#185]
How to load zuul configs from db instead of yml file? And how to update zuul ratelimiter proxy when db config changes?

**Comment by marcosbarbero** [comment]
Hi @denghuichao this framework relies on `spring-boot/cloud` supported ways of externalizing configuration. If you need to store your configuration on a database I'd suggest you to you spring-cloud-config.

**Comment by denghuichao** [comment]
OK. Thanks for your answer.
