### ISSUE TITLE
 convert .yml to .properties

### ISSUE THREAD

**Issue by zackzhangzz** [marcosbarbero/spring-cloud-zuul-ratelimit#192]
- type: #optional value for each type
- user=anonymous
- origin=somemachine.com
- url=/api #url prefix
- role=user
- httpmethod=get #case insensitive

like this, how convert .yml to .properties ?

**Comment by marcosbarbero** [comment]
You can try something like this:

```
zuul.ratelimit.key-prefix=your-prefix
zuul.ratelimit.enabled=true
zuul.ratelimit.repository=REDIS
zuul.ratelimit.behind-proxy=true
zuul.ratelimit.add-response-headers=true
zuul.ratelimit.default-policy-list=[{limit=10, quota=1000, refresh-interval=60, type=[user, origin, url, httpmethod]}]
zuul.ratelimit.policy-list.myServiceId=[{limit=10, quota=1000, refresh-interval=60, type=[user, origin, url]}, {type=[user=anonymous, origin=somemachine.com, url=/api, role=user, httpmethod=get]}]
```

Let me know if it worked.

**Comment by zackzhangzz** [comment]
zuul.ratelimit.key-prefix = prefix
zuul.ratelimit.enabled = true
zuul.ratelimit.repository = REDIS
zuul.ratelimit.behind-proxy = true
zuul.ratelimit.policy-list.bm = [{limit=1, quota=10, refresh-interval=10, type=[user, origin, url]}, {type=[user=anonymous, origin=somemachine.com, url=/api, role=user, httpmethod=get]}]


Failed to bind properties under 'zuul.ratelimit.policy-list.bm' to java.util.List<com.marcosbarbero.cloud.autoconfigure.zuul.ratelimit.config.properties.RateLimitProperties$Policy>:

    Reason: No converter found capable of converting from type [java.lang.String] to type [java.util.List<com.marcosbarbero.cloud.autoconfigure.zuul.ratelimit.config.properties.RateLimitProperties$Policy>]

**Comment by marcosbarbero** [comment]
Something like this should do:

```
zuul.ratelimit.key-prefix=your-prefix
zuul.ratelimit.enabled=true
zuul.ratelimit.repository=REDIS
zuul.ratelimit.behind-proxy=true
zuul.ratelimit.add-response-headers=true
zuul.ratelimit.default-policy-list.limit=10
zuul.ratelimit.default-policy-list.quota=1000
zuul.ratelimit.default-policy-list.refresh-interval=60
zuul.ratelimit.default-policy-list.type=user
zuul.ratelimit.default-policy-list.httpmethod=get
```

**Comment by marcosbarbero** [comment]
Here's a full working sample:

```properties
zuul.ratelimit.enabled=true
zuul.ratelimit.key-prefix=your-prefix
zuul.ratelimit.repository=REDIS
zuul.ratelimit.behind-proxy=true
zuul.ratelimit.add-response-headers=true

zuul.ratelimit.default-policy-list[0].limit=10
zuul.ratelimit.default-policy-list[0].quota=1000
zuul.ratelimit.default-policy-list[0].refresh-interval=60

# Adding multiple rate limit type
zuul.ratelimit.default-policy-list[0].type[0]=user
zuul.ratelimit.default-policy-list[0].type[1]=origin
zuul.ratelimit.default-policy-list[0].type[2]=url
zuul.ratelimit.default-policy-list[0].type[3]=httpmethod

# Adding multiple policies for the same service
zuul.ratelimit.policy-list.myServiceId[0].limit=10
zuul.ratelimit.policy-list.myServiceId[0].quota=1000
zuul.ratelimit.policy-list.myServiceId[0].refresh-interval=60
zuul.ratelimit.policy-list.myServiceId[0].type[0]=user
zuul.ratelimit.policy-list.myServiceId[0].type[1]=origin
zuul.ratelimit.policy-list.myServiceId[0].type[2]=url
zuul.ratelimit.policy-list.myServiceId[1].type[0]=user=anonymous
zuul.ratelimit.policy-list.myServiceId[1].type[1]=origin=somemachine.com
zuul.ratelimit.policy-list.myServiceId[1].type[2]=url_pattern=/api/*/payment
zuul.ratelimit.policy-list.myServiceId[1].type[3]=role=user
zuul.ratelimit.policy-list.myServiceId[1].type[4]=httpmethod=get
```

**Comment by digithinkers** [comment]
Hi @marcosbarbero  ,
 I heave copied properties  from the github project but im unable to apply rate limiting for specific user or role.if i try to assign role I'm getting Not supported exception screenshot attached
![image](https://user-images.githubusercontent.com/57535523/74725507-cba23f00-525f-11ea-95cf-810ef07ff2d2.png)

 My configuration is 
zuul:
  ratelimit:
    enabled: true
    repository: JPA
    behind-proxy: true
    add-response-headers: true
    policy-list:
      test-service:
        - limit: 10 #optional - request number limit per refresh interval window
          quota: 1000 #optional - request time limit per refresh interval window (in seconds)
          refresh-interval: 60 #default value (in seconds)
          type: #optional
            - role=admin 
if I'm missing anything kindly let me know

**Comment by DBelf** [comment]
Hey @digithinkers, thanks for reaching out. Can you maybe open a new issue so we can keep it ogranized :)?
To help you a little bit on the way though: it looks like you're using the yml format for your configuration.
Yml files are very strict on whitespace so it's possible that the formatting got messed up when you were copying the configuration.
Can you maybe use insert code when copying the configuration so we can check if the formatting is correct/validate it with the same settings?

**Comment by digithinkers** [comment]
Hi @DBelf ,
   Thanks for the quick response ,i'm creating a new issue right know i have checked my configuration for white space but that doesn't seems to be the issue
