### ISSUE TITLE
bean of type 'org.springframework.cloud.netflix.zuul.filters.RouteLocator' that could not be found

### ISSUE THREAD

**Issue by bp32795** [marcosbarbero/spring-cloud-zuul-ratelimit#196]
spring-cloud-starter-netflix-zuul and spring-cloud-zuul-ratelimit are both in the POM.

Application,properties

zuul.ratelimit.enabled=true
zuul.ratelimit.repository=REDIS
zuul.ratelimit.add-response-headers=true

zuul.ratelimit.policy-list.myServiceId[0].limit=5
zuul.ratelimit.policy-list.myServiceId[0].refresh-interval=60
zuul.ratelimit.policy-list.myServiceId[0].type[0]=url=/api
zuul.routes.myServiceId[0].path=/api

Description:

Parameter 2 of method rateLimiterPreFilter in com.marcosbarbero.cloud.autoconfigure.zuul.ratelimit.RateLimitAutoConfiguration required a bean of type 'org.springframework.cloud.netflix.zuul.filters.RouteLocator' that could not be found.

The following candidates were found but could not be injected:
          - Bean method 'discoveryRouteLocator' in 'ZuulProxyAutoConfiguration' not loaded because @ConditionalOnBean (types: org.springframework.cloud.netflix.zuul.ZuulProxyMarkerConfiguration$Marker; SearchStrategy: all) did not find any beans of type org.springframework.cloud.netflix.zuul.ZuulProxyMarkerConfiguration$Marker
          - Bean method 'primaryRouteLocator' in 'ZuulServerAutoConfiguration' not loaded because @ConditionalOnBean (types: org.springframework.cloud.netflix.zuul.ZuulServerMarkerConfiguration$Marker; SearchStrategy: all) did not find any beans of type org.springframework.cloud.netflix.zuul.ZuulServerMarkerConfiguration$Marker
          - Bean method 'simpleRouteLocator' in 'ZuulServerAutoConfiguration' not loaded because @ConditionalOnBean (types: org.springframework.cloud.netflix.zuul.ZuulServerMarkerConfiguration$Marker; SearchStrategy: all) did not find any beans of type org.springframework.cloud.netflix.zuul.ZuulServerMarkerConfiguration$Marker

Action:

Consider revisiting the entries above or defining a bean of type 'org.springframework.cloud.netflix.zuul.filters.RouteLocator' in your configuration.

**Comment by marcosbarbero** [comment]
Do you have zuul enabled on your project?

**Comment by bp32795** [comment]
@EnableZuulServer is in the boot class.

**Comment by marcosbarbero** [comment]
For some reason the `@Bean` `org.springframework.cloud.netflix.zuul.filters.RouteLocator` is not found, can you share a minimum project reproducing the issue?

**Comment by bp32795** [comment]
We were able to fix it, unrelated to this.
