### ISSUE TITLE
InMemoryRateLimiter

### ISSUE THREAD

**Issue by bensonHe** [marcosbarbero/spring-cloud-zuul-ratelimit#22]
1. good job, but  when i use it in my project (the  version is Brixton.RELEASE) ,  can't find this class  org.springframework.cloud.netflix.zuul.util.ZuulRuntimeException

**Comment by marcosbarbero** [comment]
Hello, thanks for sharing.

The current version is compatible with `Camden` release and that class you mentioned was moved.

I'll try to find a way to keep backwards compatibility but I'm still not sure how to achieve that.

**Comment by bensonHe** [comment]
thanks u answer . an advise
in this method com.marcosbarbero.cloud.autoconfigure.zuul.ratelimit.config.repository.AbstractRateLimiter.  consume() . if I use the InMemoryRateLimiter.   I think  use the synchronized will let it be more slowly  .

**Comment by marcosbarbero** [comment]
@bensonHe good catch, it actually changed types over the time. I was using [WeakHashMap](https://docs.oracle.com/javase/7/docs/api/java/util/WeakHashMap.html) at first.

**Comment by bensonHe** [comment]
maybe  not. because Math.max(-1, rate.getRemaining() - 1)  not atomic operation.  Ignore my advice

**Comment by bensonHe** [comment]
Maye you need create a  thread to clean the memory of ConcurrentHashMap.   because  rate

**Comment by bensonHe** [comment]
in class com.marcosbarbero.cloud.autoconfigure.zuul.ratelimit.config.repository.InMemoryRateLimiter#ConcurrentHashMap. the repository will out of memory. maybe you can use guava cache to insterd

**Comment by lchayoun** [comment]
@bensonHe using cache will result in data lost of the rate limit
How many different keys do you expect?

**Comment by bensonHe** [comment]
if i user 
- user
- url

,. the new user will register ervery day, so the keys will grow ervery day

**Comment by lchayoun** [comment]
why every day? it is the same user and the same url...

**Comment by bensonHe** [comment]
new user will register,   the new  user have different keys. so  the keys will be added... 

ex:   

user A visit url a.com/test   . a key save
now user B register.  
user B visit url a.com/test  . new key added

....
user C,D,E,F,G... and so on  register.   visit url a.com

**Comment by marcosbarbero** [comment]
What if I move from `ConcurrentHashMap` to [WeakHashMap](https://docs.oracle.com/javase/7/docs/api/java/util/WeakHashMap.html)?

**Comment by lchayoun** [comment]
I think that between cache and WeakHashMap, cache will be better (also same logic as using redis - to an extent).

But, since in order to use a custom implementation of the repository, you only need to create a bean that extends the `AbstractRateLimiter` class and change it to cache or anything else.

InMemoryRateLimiter is a good implementation, with proper monitoring of the gateways the memory shouldn't be a problem.

My suggestion is to keep the current implementation which is good and allows easy customization.

**Comment by bensonHe** [comment]
In my project  ,  I use the guava cache...
