### ISSUE TITLE
Failed to bind properties under 'zuul.ratelimit.repository' to com.marcosbarbero.cloud.autoconfigure.zuul.ratelimit.config.properties.RateLimitRepository

### ISSUE THREAD

**Issue by BloodFlame** [marcosbarbero/spring-cloud-zuul-ratelimit#237]
Description:

[The same problem](https://github.com/marcosbarbero/spring-cloud-zuul-ratelimit/issues/122#issue-370953602) came out with me.

```
2019-11-04 10:00:31.857 ERROR [cc-gateway,,,] 11220 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'zuul.ratelimit.repository' to com.marcosbarbero.cloud.autoconfigure.zuul.ratelimit.config.properties.RateLimitRepository:

    Property: zuul.ratelimit.repository
    Value: redis
    Origin: "zuul.ratelimit.repository" from property source "bootstrapProperties"
    Reason: 0

Action:

Update your application's configuration

```
And my java version is:
```
java version "1.8.0_20"
Java(TM) SE Runtime Environment (build 1.8.0_20-b26)
Java HotSpot(TM) 64-Bit Server VM (build 25.20-b23, mixed mode)
```

After I updated JDK :
```
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)
```
Problem was solved.

I don't know how it happend, but I think it was java version 1.8.0_20 that lead to it.
Have your problem solved? Hope it can help you @ptlive1001.

**Comment by marcosbarbero** [comment]
So, I guess I can close this issue? :)

**Comment by BloodFlame** [comment]
Yeah, but it would be nice if you can fix it. :-P

**Comment by marcosbarbero** [comment]
What’s the OS used by you? Is it Windows 10 as well?

**Comment by BloodFlame** [comment]
No, it's CentOS7.2.
```
[ydm@top ~]$ cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core) 
```

**Comment by marcosbarbero** [comment]
It's a little tricky to fix this one for at least these two reasons:

1. this project relies on spring boot's configuration binding and does nothing customized 
2. the issue seems to be a JDK/JVM related issue

I sincerely don't know how to fix it at this moment.

**Comment by BloodFlame** [comment]
It doesn't matter. We can avoid it anyway.
