### ISSUE TITLE
Race condition in AbstractRateLimitFilter.java

### ISSUE THREAD

**Issue by gonedays** [marcosbarbero/spring-cloud-zuul-ratelimit#246]
Hi, just read the source code in com.marcosbarbero.cloud.autoconfigure.zuul.ratelimit.filters.AbstractRateLimitFilter.java,  the boolean field `alreadyLimited ` may cause concurrency problem, if I'am wrong, please correct me.
The value of alreadyLimited filed is changed in line 63 and 73, but the filter is singleton, according to java doc of ZuulFilter: "By default ZuulFilters are static; they don't carry state."

**Comment by marcosbarbero** [comment]
Good catch @gonedays, I'll work on a solution for this asap.
You can expect a new version fixing it by the end of the week.

**Comment by marcosbarbero** [comment]
@gonedays [v2.2.7.RELEASE](https://github.com/marcosbarbero/spring-cloud-zuul-ratelimit/releases/tag/v2.2.7.RELEASE) was released and should be available on Maven Central in the next few hours.
