### ISSUE TITLE
I cannot catch ZuulException(429 TOO_MANY_REQUESTS)

### ISSUE THREAD

**Issue by cancy2224** [marcosbarbero/spring-cloud-zuul-ratelimit#250]
The class with "@Configuration"
```java
    @Bean
    public RateLimiterErrorHandler rateLimitErrorHandler() {
        return new CustomRateLimiterErrorHandler();
    }
```

and my custom class "CustomRateLimiterErrorHandler"

```java
public class CustomRateLimiterErrorHandler implements RateLimiterErrorHandler {
    private static final Logger logger = LoggerFactory.getLogger(CustomRateLimiterErrorHandler.class);
    @Override
    public void handleSaveError(String key, Exception e) {
        logger.error("handleSaveError");
    }

    @Override
    public void handleFetchError(String key, Exception e) {
        logger.error("handleFetchError");
    }

    @Override
    public void handleError(String msg, Exception e) {
        logger.error("handleError");
    }
}
```

**Comment by marcosbarbero** [comment]
Hi @cancy2224, I believe you're misunderstanding the usage of the `RateLimiterErrorHandler`. From the javadocs:

>Handles the backend storage errors.

It means it's only used to handle errors that happen during the storage of a `Rate`.

The `429 - Too many requests` is the error thrown when the rate limit has exceeded.

**Comment by wanglan1991** [comment]
hi, could you please tell me how I can add an ip in the Whitelist, my config is "zuul.ratelimit.default-policy.type=origin"
