### ISSUE TITLE
"quota" settings issue

### ISSUE THREAD

**Issue by fanxiangchao** [marcosbarbero/spring-cloud-zuul-ratelimit#253]
Version: v1.7.5.RELEASE 
java class: RedisRateLimiter  at line: 66-70
when setting "quota", the key is incremented for the first time, but it may not return 1,  "current" equal to "usage"，so "handleExpiration" method will not execute
current = redisTemplate.opsForValue().increment(key, usage);
if (current != null && current.equals(1L)) {
                handleExpiration(key, refreshInterval);
}

**Comment by vasilaio** [comment]
this issues was fixed in #206
