### ISSUE TITLE
Add possibility to react on rate limit exceeded  

### ISSUE THREAD

**Issue by vasilaio** [marcosbarbero/spring-cloud-zuul-ratelimit#255]
I need a way to "catch" the moment when a rate limit is reached and react appropriately (for example send an email, save the information in the audit database). 
A solution will be to send an application event from zuul pre filter.
This may fix #250

**Comment by marcosbarbero** [comment]
Hi @vasilaio, what do you mean by an application event? The application already throws an exception. You could add your own `ZuulFilter` to catch this exception and act upon it.

**Comment by vasilaio** [comment]
Hi @marcosbarbero, I meant the ApplicationEvent. I will try to create a PR in the next days if it is ok.

**Comment by marcosbarbero** [comment]
that's ok, whenever you have time!

**Comment by sharunthomas** [comment]
How can I add ZuulFilter to catch the 429 error thrown from zuul?

**Comment by sharunthomas** [comment]
I'm using 
` compile group: 'com.marcosbarbero.cloud', name: 'spring-cloud-zuul-ratelimit', version: '1.7.5.RELEASE'`

I tried to create a zuul filter but it is not working as expected

**Comment by marcosbarbero** [comment]
Hi @sharunthomas, [the 1.7.x series has reached its end of life](https://github.com/marcosbarbero/spring-cloud-zuul-ratelimit/tree/1.7.x#spring-cloud-zuul-rate-limit-eol). To intercept the event implemented to fix this issue you must use the latest versions.

[Here you can find how to do it](https://github.com/marcosbarbero/spring-cloud-zuul-ratelimit#event-handling).
