### ISSUE TITLE
ratelimit  How to add a whitelist

### ISSUE THREAD

**Issue by wanglan1991** [marcosbarbero/spring-cloud-zuul-ratelimit#259]
hi, could you please tell me how I can add an ip in the Whitelist, my config is "zuul.ratelimit.default-policy.type=origin"

**Comment by wanglan1991** [comment]
ip  whitelist

**Comment by marcosbarbero** [comment]
Hi @wanglan1991, this library is not meant for IP whitelisting.
The feature you can achieve by using this library is to set a certain limit of request per specific origins.

**Comment by vasilaio** [comment]
@marcosbarbero maybe a blacklist/whitelist option will be nice? I have a requirement to blacklist the IP if there was more the 100 requests in 2 minutes but skip if the IP is internal (from automation test).

**Comment by marcosbarbero** [comment]
Closing in favor of #385
