### ISSUE TITLE
Class cast exception in RedisRateLimiter

### ISSUE THREAD

**Issue by vasilaio** [marcosbarbero/spring-cloud-zuul-ratelimit#268]
Hi @marcosbarbero,
in #254 a bug was introduced.
```java
java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.String
	at org.springframework.data.redis.serializer.StringRedisSerializer.serialize(StringRedisSerializer.java:36) ~[spring-data-redis-2.2.3.RELEASE.jar:2.2.3.RELEASE]
	at org.springframework.data.redis.core.AbstractOperations.rawValue(AbstractOperations.java:127) ~[spring-data-redis-2.2.3.RELEASE.jar:2.2.3.RELEASE]
	at org.springframework.data.redis.core.DefaultValueOperations.setIfAbsent(DefaultValueOperations.java:307) ~[spring-data-redis-2.2.3.RELEASE.jar:2.2.3.RELEASE]
	at com.marcosbarbero.cloud.autoconfigure.zuul.ratelimit.config.repository.RedisRateLimiter.calcRemaining(RedisRateLimiter.java:66) [classes/:na]
```
Because we try to set a `long` value with ``` java DefaultValueOperations.Boolean setIfAbsent(K key, V value, long timeout, TimeUnit unit)```, but the RedisTemplate instance is StringRedisTemplate, https://github.com/marcosbarbero/spring-cloud-zuul-ratelimit/blob/557cc5a41d8116315cd8efbe031d1047804b6b6b/spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/RateLimitAutoConfiguration.java#L144

I don't know if this is a misconfiguration from our side or it is a bug in spring, because the ValueOperation from RedisTemplate allows object as parameter but internally the generics are ignored and StringTemplate does not check the parameter type in [AbstractOperations. rawValue](https://github.com/spring-projects/spring-data-redis/blob/64f3e8f6a3d6f60a3ec4c1eb9610c2c7bdb33d34/src/main/java/org/springframework/data/redis/core/AbstractOperations.java#L121)  

The easy way to fix this issue is to convert usage to String in https://github.com/marcosbarbero/spring-cloud-zuul-ratelimit/blob/557cc5a41d8116315cd8efbe031d1047804b6b6b/spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/repository/RedisRateLimiter.java#L66. This solution will fix this issue, but the problem with calling StringTemplate with non string values will remain for the future fixes.
We could inject StringRedisTemplate instead of just RedisTemplate in RedisRateLimiter?

**Comment by marcosbarbero** [comment]
It's a very good catch, I totally missed this!
I'll be changing it and releasing a new version asap.
