### ISSUE TITLE
Allow to hide keys in response header

### ISSUE THREAD

**Issue by vasilaio** [marcosbarbero/spring-cloud-zuul-ratelimit#282]
**Is your feature request related to a problem? Please describe.**
I don't want to show my rate limit keys in response headers. According to [standard](https://tools.ietf.org/id/draft-polli-ratelimit-headers-00.html), the RateLimit response headers are predefined strings and contains no other information.

**Describe the solution you'd like**
Add an option to hide the keys from response headers. The existing option, 'add-response-headers', can be enhanced to support enum values (e.g. none, standard, verbose) or a new option like 'headers-verbosity' could be added in addition to this option (backwards compatibility).

**Comment by marcosbarbero** [comment]
Thanks @vasilaio, it's a very interesting feature. I liked the first option, but it would be a breaking change unless we add `TRUE` as an option to keep the functionality as is today. However, we could add this `TRUE` value already deprecated and warn the users to use different values.

**Comment by marcosbarbero** [comment]
@vasilaio I'm thinking about make a new release by the next week, would you like this feature to be in that release?

**Comment by vasilaio** [comment]
@marcosbarbero it will be nice to have it. I will try to provide a PR. As you suggested, I want to add a new properties to 'add-response-headers' ('none', 'standard', 'verbose') and deprecate the old one. Unfortunately I didn't managed to generate the correct metadata in 'spring-configuration-metadata.json'.
