### ISSUE TITLE
Rate limiting for specfic Role or User 

### ISSUE THREAD

**Issue by digithinkers** [marcosbarbero/spring-cloud-zuul-ratelimit#298]
**Describe the bug**
Hi @DBelf ,
            As per instruction I'm placing my issue here ,im using zuul rate limiter with zuul api gateway,it works fine with with default policy and with policy list. But when ever i define specific role or user name e.g user=admin or role=admin im getting error and for some unknown reason i can't set role as first type

zuul:
  ratelimit:
    enabled: true
    repository: JPA
    behind-proxy: true
    add-response-headers: true
    policy-list:
      test-service:
        - limit: 10 #optional - request number limit per refresh interval window
          quota: 1000 #optional - request time limit per refresh interval window (in seconds)
          refresh-interval: 60 #default value (in seconds)
          type: #optional
            - role=admin

I'm getting 
![image](https://user-images.githubusercontent.com/57535523/74731734-74559c00-526a-11ea-8fbe-12ade6b12fe6.png)
And when i define it as
zuul:
  ratelimit:
    enabled: true
    repository: JPA
    behind-proxy: true
    add-response-headers: true
    policy-list:
      test-service:
        - limit: 10 #optional - request number limit per refresh interval window
          quota: 1000 #optional - request time limit per refresh interval window (in seconds)
          refresh-interval: 60 #default value (in seconds)
          type: #optional
           - user = test
            - role=admin

Code runs but rate limiting gets ineffective 
**Expected behavior**
As per documentation user with role admin shoudlnt have more than 10 hits.

**Environment & Versioning (please complete the following information):**
 - OS: Windows 10
 - Spring Boot 2.2.2.RELEASE
 - Spring Cloud Hoxton.SR1
 - Spring Cloud Rate Limit 2.3.0.RELEASE

**Comment by marcosbarbero** [comment]
Hi @digithinkers thanks for using this library.
Do you have spring security configure at your project? 

The exception you’re getting is intentional as to get the user roles it’s mandatory to have spring security’s context configure in the application. If you don’t have it then the library can not get the user roles therefore throwing this exception.

**Comment by digithinkers** [comment]
Hi @marcosbarbero ,
    For security I'm using key-cloak  that bind its self to spring security its configuration is as follow
keycloak.realm=my-demo
keycloak.auth-server-url=http://localhost:8080/auth
keycloak.ssl-required=external
keycloak.resource=spring

keycloak.credentials.secret=xxxxxx-xxxxxxxxxxxxxxxx-xxxxxxxxxx
keycloak.securityConstraints[0].authRoles[0]=spring
keycloak.securityConstraints[0].securityCollections[0].name=protected
keycloak.securityConstraints[0].securityCollections[0].patterns[0]=/api/v1/*

keycloak.securityConstraints[1].authRoles[0]=ADMIN
keycloak.securityConstraints[1].securityCollections[0].name=protected
keycloak.securityConstraints[1].securityCollections[0].patterns[0]=/testt/*
keycloak.policy-enforcer-config.lazy-load-paths=true

and its working fine until I define specific user or role

**Comment by marcosbarbero** [comment]
Can you show me your project dependencies?

**Comment by digithinkers** [comment]
Hi @marcosbarbero ,
     My pom is 

> <dependencies>

		<dependency>
			<groupId>com.marcosbarbero.cloud</groupId>
			<artifactId>spring-cloud-zuul-ratelimit</artifactId>
			<version>2.3.0.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.keycloak</groupId>
			<artifactId>keycloak-spring-boot-starter</artifactId>
			<version>4.5.0.Final</version>
		</dependency>
		<dependency>
			<groupId>org.keycloak</groupId>
			<artifactId>keycloak-authz-client</artifactId>
			<version>4.5.0.Final</version>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>4.5.2</version>
		</dependency>
		<dependency>
			<groupId>de.codecentric</groupId>
			<artifactId>spring-boot-admin-starter-client</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-netflix-zuul</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-config</artifactId>
		</dependency>
		 <dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
		 </dependency>
		  <dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.junit.vintage</groupId>
					<artifactId>junit-vintage-engine</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
	</dependencies>

**Comment by marcosbarbero** [comment]
Hi @digithinkers thanks for the dependencies, as I mentioned before the problem is the missing dependency for `spring-security`. This project wasn't built to use keycloak,  but I do think it's a good improvement.

@DBelf @lchayoun WDYT?

**Comment by marcosbarbero** [comment]
@digithinkers aren't you missing this config? https://www.keycloak.org/docs/latest/securing_apps/#_spring_security_adapter

**Comment by DBelf** [comment]
> @DBelf @lchayoun WDYT?
From the looks of it, you need the `spring-security` dependency. This will also provide the KeycloakAdapter mentioned by @marcosbarbero. 
So hopefully adding (and maybe configuring) the `spring-security` dependency should resolve this issue

**Comment by vasilaio** [comment]
According to [Keycloak](https://www.keycloak.org/docs/latest/securing_apps/#_spring_boot_adapter)'s documentation, it seems that spring security dependencies is not required if the JavaEE security constraint:
> Currently the following embedded containers are supported and do not require any extra dependencies if using the Starter
I found a good example and explanation about this case [here](https://developers.redhat.com/blog/2017/05/25/easily-secure-your-spring-boot-applications-with-keycloak/).

**Comment by digithinkers** [comment]
Hi @vasilaio ,
       Thanks for the reference.Approach you mentioned is similar to the one I'm using .Key Cloak and spring security integration is working,Because only my mentioned roles are getting access   
![image](https://user-images.githubusercontent.com/57535523/74914505-5f9d1380-53e4-11ea-84fa-bdc2feea6064.png)
but when ever i try to assign specific role or user name in config rate limiting gets ineffective
this config work fine

> zuul:
> 
>   ratelimit:
>     enabled: true
>     repository: JPA
>     behind-proxy: true
>     add-response-headers: true
>     default-policy-list: #optional - will apply unless specific policy exists
>       - limit: 1 #optional - request number limit per refresh interval window
>         quota: 1 #optional - request time limit per refresh interval window (in seconds)
>         refresh-interval: 60 #default value (in seconds)
>         type: #optional
>           - user
>           - origin
>           - url
>           - http_method
>     policy-list:
>       test-service:
>         - limit: 10 #optional - request number limit per refresh interval window
>           quota: 10 #optional - request time limit per refresh interval window (in seconds)
>           refresh-interval: 60 #default value (in seconds)
> 
> this make rate limiting ineffective 
> zuul:
>   ratelimit:
>     enabled: true
>     repository: JPA
>     behind-proxy: true
>     add-response-headers: true
>     default-policy-list: #optional - will apply unless specific policy exists
>       - limit: 1 #optional - request number limit per refresh interval window
>         quota: 1 #optional - request time limit per refresh interval window (in seconds)
>         refresh-interval: 60 #default value (in seconds)
>         type: #optional
>           - user
>           - origin
>           - url
>           - http_method
>     policy-list:
>       test-service:
>         - limit: 10 #optional - request number limit per refresh interval window
>           quota: 10 #optional - request time limit per refresh interval window (in seconds)
>           refresh-interval: 60 #default value (in seconds)
>           type: #optional value for each type
>             - role=ADMIN

**Comment by DBelf** [comment]
I think you're declaring the type incorrectly in your `application.yml`. Take note that the type configuration happens in an array. From the examples, it looks like you're not setting the correct configuration. However it's hard to determine if the `yml` snippet isn't indented :).
Hopefully this example will help you.
What I think you're doing:
```
zuul:
  ratelimit:
    ...
    policy-list:
      myServiceId:
        - limit: 10 #optional - request number limit per refresh interval window
          quota: 1000 #optional - request time limit per refresh interval window (in seconds)
          refresh-interval: 60 #default value (in seconds)
          type: # you're trying to configure this field with the actual type configuration. This only declares the types.
            - user # this can only be set to a string, not a complex object
        - type: # you should be configuring the type here
            - role=ADMIN
        - type: # any other complex type configuration you want to set
           ...
```

**Comment by digithinkers** [comment]
Hi @DBelf ,
   thanks for config file.
    I'm placing screenshot of my config and the error I'm getting here so you can have the better idea
![image](https://user-images.githubusercontent.com/57535523/74929096-a4cd3f80-53fc-11ea-9a90-6ea85fd052ec.png)

**Comment by digithinkers** [comment]
I  reverted back to release 2.2.1.RELEASE error didn't change but log were little clear 
![image](https://user-images.githubusercontent.com/57535523/74930817-34282200-5400-11ea-95fb-8fd28d8d269f.png)

**Comment by digithinkers** [comment]
@DBelf ,
adding "-" before type is breaking it to another policy i have define only one policy, but it is being broken  into two policies
![image](https://user-images.githubusercontent.com/57535523/74936167-79058600-540b-11ea-8318-5cb8cd05b4d2.png)

**Comment by vasilaio** [comment]
@digithinkers,
a) regarding your initial problem... you have two options: 
1. add spring security dependency + keycloak dependencies (fallow docs or the link)
2. keep your current pom but define a custom bean of [RateLimitUtils](spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/RateLimitUtils.java) and extract the user roles.

b) regarding yml file... for each policy it is mandatory to have limit and/or quota. In your configuration the last two lines defines a new policy but it misses this attributes (the example in README is misguided).

**Comment by digithinkers** [comment]
@vasilaio ,
            Thanks for the feed back .I have gone with option number one that is 

> a) regarding your initial problem... you have two options:

    add spring security dependency + keycloak dependencies (fallow docs or the link)
    keep your current pom but define a custom bean of RateLimitUtils and extract the user roles.
this is what i have done 
I define custom bean of Rate limit Utils

`import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;

import org.springframework.context.annotation.Primary;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;

import com.marcosbarbero.cloud.autoconfigure.zuul.ratelimit.config.properties.RateLimitProperties;
import com.marcosbarbero.cloud.autoconfigure.zuul.ratelimit.support.DefaultRateLimitUtils;

/**
 * @author digithinkers
 *
 */
@Primary
@Service
public class RateLimitImpl extends DefaultRateLimitUtils {

	/**
	 * @param properties
	 */
	public RateLimitImpl(RateLimitProperties properties) {
		super(properties);
		// TODO Auto-generated constructor stub
	}

	/**
	 * @param properties
	 */

	@Override
	public Set<String> getUserRoles() {
		Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
		Set<String> test=new HashSet<>();
		for (int i = 0; i < authentication.getAuthorities().size(); i++) {
			authentication.getAuthorities().forEach((x)->{test.add(x.getAuthority());});
		} 
		return test;
	}
}

`

`Injected RatelimitImpl in custom RateLimitKeyGenerator 

    @Bean
    public RateLimitKeyGenerator ratelimitKeyGenerator(RateLimitProperties properties, RateLimitUtils rateLimitUtils) {
    	RateLimitImpl test=new RateLimitImpl(properties);
        return new DefaultRateLimitKeyGenerator(properties, test) {
            @Override
            public String key(HttpServletRequest request, Route route, RateLimitProperties.Policy policy) {
            	return super.key(request, route, policy) + ":" + request.getMethod();
            }
        };
    }`

my config looks like 

> zuul:
  ratelimit:
    enabled: true
    repository: JPA
    behind-proxy: true
    add-response-headers: true
    default-policy-list: #optional - will apply unless specific policy exists
      - limit: 1 #optional - request number limit per refresh interval window
        quota: 1 #optional - request time limit per refresh interval window (in seconds)
        refresh-interval: 60 #default value (in seconds)
        type: #optional
    policy-list:
      test-service:
        - limit: 10 #optional - request number limit per refresh interval window
          quota: 1000 #optional - request time limit per refresh interval window (in seconds)
          refresh-interval: 60 #default value (in seconds)
          type: # you should be configuring the type here, should be prefixed with the  "-"
            - role=ROLE_B
        - limit: 5 #optional - request number limit per refresh interval window
          quota: 5 #optional - request time limit per refresh interval window (in seconds)
          refresh-interval: 60 #default value (in seconds)
          type: # you should be configuring the type here, should be prefixed with the  "-"
            - role=ROLE_A

**Comment by vasilaio** [comment]
hi @digithinkers, 
If you added the spring security in the classpath, there is no need to define a custom bean (see [SecuredRateLimitUtils](https://github.com/marcosbarbero/spring-cloud-zuul-ratelimit/blob/master/spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/support/SecuredRateLimitUtils.java). 
Regarding your yml config, please use yml [code formatter](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) (\```yml).
