### ISSUE TITLE
Use sonarqube static code analysis

### ISSUE THREAD

**Issue by lchayoun** [marcosbarbero/spring-cloud-zuul-ratelimit#30]
sonar provides better static code analysis of issues, code branches testing and much more.
Free for open source: https://about.sonarcloud.io/

**Comment by marcosbarbero** [comment]
Really nice, I had it in my TODO list long ago and I just forgot about that.

**Comment by lchayoun** [comment]
@marcosbarbero great work!
I think you can add the markup: 
[![Quality Gate](https://sonarcloud.io/api/badges/gate?key=com.marcosbarbero.cloud:spring-cloud-zuul-ratelimit-parent)](https://sonarcloud.io/dashboard/index/com.marcosbarbero.cloud:spring-cloud-zuul-ratelimit-parent)

also, there seems to be an issue with the coverage.

The github plugin would be great addition:
https://docs.sonarqube.org/display/PLUG/GitHub+Plugin

**Comment by marcosbarbero** [comment]
thanks @lchayoun, I was looking into it right now!
I'll let you know once I've all set

**Comment by lchayoun** [comment]
@marcosbarbero maybe this will help:
https://docs.sonarqube.org/display/PLUG/Usage+of+JaCoCo+with+Java+Plugin
it seems the install should run after the jacoco prepare agent

Also for the pull request stamping:
https://github.com/SonarSource/sonarqube/blob/master/.travis.yml - notice the "script: ./travis.sh"
https://github.com/SonarSource/sonarqube/blob/master/travis.sh

**Comment by marcosbarbero** [comment]
@lchayoun I'm reopening this issue until I apply those fix for code coverage and PR stamping.
