### ISSUE TITLE
it seem not need to operate redis again when request time is not null.

### ISSUE THREAD

**Issue by maketubo** [marcosbarbero/spring-cloud-zuul-ratelimit#323]
https://github.com/marcosbarbero/spring-cloud-zuul-ratelimit/blob/37f01a6cc609c8971f3d5bd2f3668f868136d00e/spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/repository/RedisRateLimiter.java#L41-L49
  When requestTime is not null, usage will be zero. Does it make sense to do redis set command again although redis command is very fast? 
  In other word,  calcRemainingLimit may not be called when requestTime is not null in AbstractCacheRateLimiter.
```
    @Override
    public synchronized Rate consume(Policy policy, String key, Long requestTime) {
        final Duration refreshInterval = policy.getRefreshInterval();
        final Long quota = policy.getQuota() != null ? policy.getQuota().toMillis() : null;
        final Rate rate = new Rate(key, policy.getLimit(), quota, null, null);
        if(requestTime == null){
            calcRemainingLimit(policy.getLimit(), refreshInterval, requestTime, key, rate);
        }
        calcRemainingQuota(quota, refreshInterval, requestTime, key, rate);

        return rate;
    }
```

**Comment by marcosbarbero** [comment]
@maketubo it will be fixed on #348, thanks for your contribution.
