### ISSUE TITLE
How to load configuration dynamically

### ISSUE THREAD

**Issue by whd120130** [marcosbarbero/spring-cloud-zuul-ratelimit#334]
How to load configuration dynamically？ thanks

**Comment by rajakumar17** [comment]
To dynamically load configuration, I updated the RateLimitProperties with the policylist.

  @Autowired
  private ZuulProperties zuulProperties;

  @Autowired
  private RateLimitProperties rateLimitProperties;

  @Autowired
  private ZuulHandlerMapping zuulHandlerMapping;

zuulProperties.getRoutes().put(id, zuulConfig.getRoute());
rateLimitProperties.getPolicyList().put(id, zuulConfig.getPolicyList());
zuulHandlerMapping.setDirty(true);

**Comment by whd120130** [comment]
With demo Do you？

**Comment by marcosbarbero** [comment]
This library relies on Spring Boot/Spring Cloud mechanism to load application properties/configuration. You can follow this link to get more information about it https://spring.io/guides/gs/centralized-configuration/
