### ISSUE TITLE
Cannot resolve configuration property 'zuul.ratelimit'

### ISSUE THREAD

**Issue by flyhero** [marcosbarbero/spring-cloud-zuul-ratelimit#34]
in my application.properties

**Comment by lchayoun** [comment]
@flyhero can you explain some more?
what exactly is the issue? is your app not starting? rate limit not working?

**Comment by flyhero** [comment]
@lchayoun rate limit not working, i guess RateLimitProperties can not found my application.properties

**Comment by lchayoun** [comment]
@flyhero Ok, I guess that other properties are working from this file, right?
Can you please write the file content?

**Comment by flyhero** [comment]
@lchayoun thanks, Although the tips is 'cannot resolve...', but it can work ，this is my fault ,my dynamic route configuration is wrong.
