### ISSUE TITLE
when to  support  custom RateLimitProperties.Policy？ thanks

### ISSUE THREAD

**Issue by huangll** [marcosbarbero/spring-cloud-zuul-ratelimit#343]
**Describe the question**
I want to difine different limit for different user.

**Additional context**
when to  support  custom RateLimitProperties.Policy？ thanks

**Comment by lchayoun** [comment]
Can you explain more?
What is missing?

**Comment by huangll** [comment]
Generate different limit value for different user .

---------------------------------------------------------------------------------------------
enabled: true
    repository: REDIS
    behind-proxy: true
    add-response-headers: true
    default-policy-list: 
      - limit: 2 
        quota: 10 
        refresh-interval: 2 
        type: 
          - user

**Comment by marcosbarbero** [comment]
You can do that by specifying the username at the type, something like this:

```
  - type:
    - user=the_username
```

**Comment by marcosbarbero** [comment]
Closing due inactivity.
