### ISSUE TITLE
I tried to implement rate limiting in spring boot with spring cloud netflix rate limiter

### ISSUE THREAD

**Issue by Sharun94** [marcosbarbero/spring-cloud-zuul-ratelimit#344]
These are the dependencies that I added

Spring boot: 1.5.4
```
compile('org.springframework.cloud:spring-cloud-starter-netflix-zuul')
compile group: 'com.marcosbarbero.cloud', name: 'spring-cloud-zuul-ratelimit', version: '1.7.5.RELEASE'
```

properties
```properties
zuul.ratelimit.enabled=true
zuul.ratelimit.repository=JPA
zuul.ratelimit.policy-list.serviceSimple.limit=1
zuul.ratelimit.policy-list.serviceSimple.refresh-interval=60
zuul.ratelimit.policy-list.serviceSimple.type=url
zuul.ratelimit.key-prefix=rate
zuul.strip-prefix: true
```

When I try to run the application an error shows that my domain classes aren't a managed type

```
caused by: java.lang.IllegalArgumentException: Not a managed type: <My entity class>
	at org.hibernate.jpa.internal.metamodel.MetamodelImpl.managedType(MetamodelImpl.java:210) ~[hibernate-entitymanager-5.0.12.Final.jar:5.0.12.Final]
	at org.springframework.data.jpa.repository.support.JpaMetamodelEntityInformation.<init>(JpaMetamodelEntityInformation.java:70) ~[spring-data-jpa-1.11.9.RELEASE.jar:na]
	at org.springframework.data.jpa.repository.support.JpaEntityInformationSupport.getEntityInformation(JpaEntityInformationSupport.java:68) ~[spring-data-jpa-1.11.9.RELEASE.jar:na]
	at org.springframework.data.jpa.repository.support.JpaRepositoryFactory.getEntityInformation(JpaRepositoryFactory.java:173) ~[spring-data-jpa-1.11.9.RELEASE.jar:na]
	at org.springframework.data.envers.repository.support.EnversRevisionRepositoryFactoryBean$RevisionRepositoryFactory.getTargetRepository(EnversRevisionRepositoryFactoryBean.java:106) ~[spring-data-envers-1.1.9.RELEASE.jar:na]
	at org.springframework.data.envers.repository.support.EnversRevisionRepositoryFactoryBean$RevisionRepositoryFactory.getTargetRepository(EnversRevisionRepositoryFactoryBean.java:77) ~[spring-data-envers-1.1.9.RELEASE.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:200) ~[spring-data-commons-1.13.9.RELEASE.jar:na]
	at org.springframework.data.envers.repository.support.EnversRevisionRepositoryFactoryBean$RevisionRepositoryFactory.getRepository(EnversRevisionRepositoryFactoryBean.java:143) ~[spring-data-envers-1.1.9.RELEASE.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.initAndReturn(RepositoryFactoryBeanSupport.java:277) ~[spring-data-commons-1.13.9.RELEASE.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:263) ~[spring-data-commons-1.13.9.RELEASE.jar:na]
	at org.springframework.data.jpa.repository.support.JpaRepositoryFactoryBean.afterPropertiesSet(JpaRepositoryFactoryBean.java:101) ~[spring-data-jpa-1.11.9.RELEASE.jar:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	... 42 common frames omitted
```

**Comment by marcosbarbero** [comment]
Hi @Sharun94 I've got a couple of questions for you:
- Does your application work without the rate limit module?
- Does your Zuul Gateway also access a database/schema/tables other than the one required for the rate limiter?

**Comment by Sharun94** [comment]
- Yes

- No

**Comment by Sharun94** [comment]
I have an update,
I tried @EntityScan to explicitly scan the entity classes, so the error before changed and got a new one
==>
Parameter 2 of method rateLimiterPreFilter in com.marcosbarbero.cloud.autoconfigure.zuul.ratelimit.RateLimitAutoConfiguration required a bean of type 'org.springframework.cloud.netflix.zuul.filters.RouteLocator' that could not be found.
	- Bean method 'discoveryRouteLocator' not loaded because @ConditionalOnBean (types: org.springframework.cloud.netflix.zuul.ZuulProxyMarkerConfiguration$Marker; SearchStrategy: all) did not find any beans
	- Bean method 'primaryRouteLocator' not loaded because @ConditionalOnBean (types: org.springframework.cloud.netflix.zuul.ZuulServerMarkerConfiguration$Marker; SearchStrategy: all) did not find any beans
	- Bean method 'simpleRouteLocator' not loaded because @ConditionalOnBean (types: org.springframework.cloud.netflix.zuul.ZuulServerMarkerConfiguration$Marker; SearchStrategy: all) did not find any beans

**Comment by marcosbarbero** [comment]
Can you share your application somewhere?

**Comment by sharunthomas** [comment]
sry I cannot do that

**Comment by sharunthomas** [comment]
Do you have any Idea Why this is happening

Parameter 2 of method rateLimiterPreFilter in com.marcosbarbero.cloud.autoconfigure.zuul.ratelimit.RateLimitAutoConfiguration required a bean of type 'org.springframework.cloud.netflix.zuul.filters.RouteLocator' that could not be found.
- Bean method 'discoveryRouteLocator' not loaded because @ConditionalOnBean (types: org.springframework.cloud.netflix.zuul.ZuulProxyMarkerConfiguration$Marker; SearchStrategy: all) did not find any beans
- Bean method 'primaryRouteLocator' not loaded because @ConditionalOnBean (types: org.springframework.cloud.netflix.zuul.ZuulServerMarkerConfiguration$Marker; SearchStrategy: all) did not find any beans
- Bean method 'simpleRouteLocator' not loaded because @ConditionalOnBean (types: org.springframework.cloud.netflix.zuul.ZuulServerMarkerConfiguration$Marker; SearchStrategy: all) did not find any beans

**Comment by sharunthomas** [comment]
I cannot share because of the confidential nature of the project. This is a simple Spring boot 1.5X application with hibernate. It was working perfectly, I added spring cloud with version: =>
ext {
    springCloudVersion = 'Edgware.SR4'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

dependencies {

    compile('org.springframework.cloud:spring-cloud-starter-netflix-zuul')
    compile group: 'com.marcosbarbero.cloud', name: 'spring-cloud-zuul-ratelimit', version: '1.7.5.RELEASE'

}

And after this on startup, it shows the above error

**Comment by sharunthomas** [comment]
**build.gradle**

buildscript {
    ext {
        springBootVersion = '1.5.9.RELEASE'
    }
    repositories {
        mavenCentral()
        jcenter()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
        classpath "io.spring.gradle:dependency-management-plugin:1.0.3.RELEASE"
        classpath('mysql:mysql-connector-java:5.1.44')
    }
}

plugins {
    id 'java'
}

apply plugin: 'java'
apply plugin: 'idea'
apply plugin: 'org.springframework.boot'
apply plugin: 'war'
apply plugin: "io.spring.dependency-management"

springBoot {
    executable = true
}

jar {
    baseName = '<basename>'
    version = '1.0.0'
}

war {
    archiveName 'ROOT.war'
}


group '<group>'
version '1.0.0'

sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    compile('org.springframework.boot:spring-boot-starter-data-jpa')
    compile('org.springframework.boot:spring-boot-starter-web')
    compile 'mysql:mysql-connector-java:5.1.44'
    compile group: 'org.springframework.data', name: 'spring-data-envers'
    testCompile('org.springframework.boot:spring-boot-starter-test')
    testCompile group: 'junit', name: 'junit', version: '4.12'
    // https://mvnrepository.com/artifact/org.aspectj/aspectjweaver
    compile group: 'org.aspectj', name: 'aspectjweaver', version: '1.9.5'
}

ext {
    springCloudVersion = 'Edgware.SR4'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

dependencies {

    compile('org.springframework.cloud:spring-cloud-starter-netflix-zuul')
    compile group: 'com.marcosbarbero.cloud', name: 'spring-cloud-zuul-ratelimit', version: '1.7.5.RELEASE'

}

**Comment by sharunthomas** [comment]
sharun94 and sharunthomas are my accounts

**Comment by marcosbarbero** [comment]
It would be great if you could apply code formatting to your inputs, it makes it a little hard to read without the formatting. You can follow this link to learn how to do it https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code

**Comment by sharunthomas** [comment]
```java
buildscript {
ext {
springBootVersion = '1.5.9.RELEASE'
}
repositories {
mavenCentral()
jcenter()
maven {
url "https://plugins.gradle.org/m2/"
}
}
dependencies {
classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
classpath "io.spring.gradle:dependency-management-plugin:1.0.3.RELEASE"
classpath('mysql:mysql-connector-java:5.1.44')
}
}

plugins {
id 'java'
}

apply plugin: 'java'
apply plugin: 'idea'
apply plugin: 'org.springframework.boot'
apply plugin: 'war'
apply plugin: "io.spring.dependency-management"

springBoot {
executable = true
}

jar {
baseName = ''
version = '1.0.0'
}

war {
archiveName 'ROOT.war'
}

group ''
version '1.0.0'

sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
mavenLocal()
mavenCentral()
}

dependencies {
compile('org.springframework.boot:spring-boot-starter-data-jpa')
compile('org.springframework.boot:spring-boot-starter-web')
compile 'mysql:mysql-connector-java:5.1.44'
compile group: 'org.springframework.data', name: 'spring-data-envers'
testCompile('org.springframework.boot:spring-boot-starter-test')
testCompile group: 'junit', name: 'junit', version: '4.12'
// https://mvnrepository.com/artifact/org.aspectj/aspectjweaver
compile group: 'org.aspectj', name: 'aspectjweaver', version: '1.9.5'
}

ext {
springCloudVersion = 'Edgware.SR4'
}

dependencyManagement {
imports {
mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
}
}

dependencies {

compile('org.springframework.cloud:spring-cloud-starter-netflix-zuul')
compile group: 'com.marcosbarbero.cloud', name: 'spring-cloud-zuul-ratelimit', version: '1.7.5.RELEASE'
}
```

**Comment by sharunthomas** [comment]
**error response**
```java
Parameter 2 of method rateLimiterPreFilter in com.marcosbarbero.cloud.autoconfigure.zuul.ratelimit.RateLimitAutoConfiguration required a bean of type 'org.springframework.cloud.netflix.zuul.filters.RouteLocator' that could not be found.
- Bean method 'discoveryRouteLocator' not loaded because @ConditionalOnBean (types: org.springframework.cloud.netflix.zuul.ZuulProxyMarkerConfiguration$Marker; SearchStrategy: all) did not find any beans
- Bean method 'primaryRouteLocator' not loaded because @ConditionalOnBean (types: org.springframework.cloud.netflix.zuul.ZuulServerMarkerConfiguration$Marker; SearchStrategy: all) did not find any beans
- Bean method 'simpleRouteLocator' not loaded because @ConditionalOnBean (types: org.springframework.cloud.netflix.zuul.ZuulServerMarkerConfiguration$Marker; SearchStrategy: all) did not find any beans
```

**Comment by sharunthomas** [comment]
**zuul properties**
`#zuul properties for rate limiting
zuul.ratelimit.enabled=true
zuul.ratelimit.repository=JPA
zuul.ratelimit.key-prefix=rate
zuul.strip-prefix: true

zuul.routes.serviceSimple.path=/api/labOrganization/simple
zuul.routes.serviceSimple.url=forward:/

zuul.ratelimit.policies.serviceSimple.limit=1
zuul.ratelimit.policies.serviceSimple.refresh-interval=60
zuul.ratelimit.policies.serviceSimple.type=url`

**Comment by sharunthomas** [comment]
**zuul properties**
```java
#zuul properties for rate limiting
zuul.ratelimit.enabled=true
zuul.ratelimit.repository=JPA
zuul.ratelimit.key-prefix=rate
zuul.strip-prefix: true

zuul.routes.serviceSimple.path=/api/labOrganization/simple
zuul.routes.serviceSimple.url=forward:/

zuul.ratelimit.policies.serviceSimple.limit=1
zuul.ratelimit.policies.serviceSimple.refresh-interval=60
zuul.ratelimit.policies.serviceSimple.type=url
```

**Comment by sharunthomas** [comment]
**zuul properties**

```java
#zuul properties for rate limiting
zuul.ratelimit.enabled=true
zuul.ratelimit.repository=JPA
zuul.ratelimit.key-prefix=rate
zuul.strip-prefix: true

zuul.routes.serviceSimple.path=/api/sample
zuul.routes.serviceSimple.url=forward:/

zuul.ratelimit.policies.serviceSimple.limit=1
zuul.ratelimit.policies.serviceSimple.refresh-interval=60
zuul.ratelimit.policies.serviceSimple.type=url
```

**Comment by marcosbarbero** [comment]
Is your application annotated with `@EnableZuulProxy`?

**Comment by sharunthomas** [comment]
no

**Comment by marcosbarbero** [comment]
Your application has to be a Zuul proxy. Otherwise, it won't work. This plugin is meant to work at the Zuul API Gateway level.

**Comment by sharunthomas** [comment]
```java

**Comment by sharunthomas** [comment]
Great, the error is gone, but rate limiting not working as expected
Do I need to add any extra codes 

- added  zuul properties in the properties file

- added dependencies as mentioned above 

**anything else needs to be added**


**This is the main class file** 
```java
@SpringBootApplication
@EntityScan("com.domain")
@EnableZuulProxy
public class ApiFrameworkApp extends SpringBootServletInitializer {

    private static final Logger logger = LoggerFactory.getLogger(ApiFrameworkApp.class);

    @Autowired
    private Environment env;

    @Override
    protected SpringApplicationBuilder configure(
            SpringApplicationBuilder application) {
        return application.sources(ApiFrameworkApp.class);
    }

    public static void main(String[] args) {
        SpringApplication.run(ApiFrameworkApp.class, args);
        logger.debug("ApiFrameworkApp Started");
    }

}
```

**Comment by sharunthomas** [comment]
**To test if the Rate is saving to the db, I put debugger points in JpaRateLimiter class in package com.marcosbarbero.cloud.autoconfigure.zuul.ratelimit.config.repository.springdata;**

But those weren't hitting when I'm calling the API

```java
package com.marcosbarbero.cloud.autoconfigure.zuul.ratelimit.config.repository.springdata;

import com.marcosbarbero.cloud.autoconfigure.zuul.ratelimit.config.Rate;
import com.marcosbarbero.cloud.autoconfigure.zuul.ratelimit.config.RateLimiter;
import com.marcosbarbero.cloud.autoconfigure.zuul.ratelimit.config.repository.AbstractRateLimiter;
import com.marcosbarbero.cloud.autoconfigure.zuul.ratelimit.config.repository.RateLimiterErrorHandler;

/**
 * JPA {@link RateLimiter} configuration.
 *
 * @author Marcos Barbero
 * @author Liel Chayoun
 * @since 2017-06-23
 */

public class JpaRateLimiter extends AbstractRateLimiter {

    private final RateLimiterRepository repository;

    public JpaRateLimiter(final RateLimiterErrorHandler rateLimiterErrorHandler,
                          final RateLimiterRepository repository) {
        super(rateLimiterErrorHandler);
        this.repository = repository;
    }

    @Override
    protected Rate getRate(String key) {
        return this.repository.findOne(key);
    }

    @Override
    protected void saveRate(Rate rate) {
        this.repository.save(rate);
    }

}

```


**application logs this when the API hits**
`Mapped URL path [/api/labOrganization/simple] onto handler of type [class org.springframework.cloud.netflix.zuul.web.ZuulController]`

**Comment by marcosbarbero** [comment]
It's probably because of your properties, instead of this:

```properties
zuul.ratelimit.policies.serviceSimple.limit=1
zuul.ratelimit.policies.serviceSimple.refresh-interval=60
zuul.ratelimit.policies.serviceSimple.type=url
```

Try this:

```properties
zuul.ratelimit.policies.serviceSimple[0].limit=1
zuul.ratelimit.policies.serviceSimple[0].refresh-interval=60
zuul.ratelimit.policies.serviceSimple[0].type[0]=url
```

**Comment by sharunthomas** [comment]
**I tried this, but not working.**
What is this 'serviceSimple' , is that something we should define?

`zuul.ratelimit.policies**.serviceSimple**[0].limit=1`

'policies' or 'policy-list'

Can you give a brief idea about these policies?

**Comment by sharunthomas** [comment]
**Great! It works now**

I changed 'policies' to  'policy-list' , now its working.
@marcosbarbero Thank you
