### ISSUE TITLE
What is the relation between zuul rate-limiting and hystrix isolation strategy?

### ISSUE THREAD

**Issue by esolve** [marcosbarbero/spring-cloud-zuul-ratelimit#354]
I'm wondering the relation between zuul rate-limiting and hystrix isolation strategies. For example, since there is semaphore isolation settings by default, which limits the number of conccurrent outgoing requests, if this is below zuul rate-limiting threshold, I think zuul rate-limiting threshold won't take effect? so if we want marcosbarbero's spring-cloud-zuul-ratelimit take effect, we should set semaphore isolation threshold to a maximum value?

**Comment by marcosbarbero** [comment]
Hi @esolve, it has been a while since I last used Hystrix, but as far as I remember, Hystrix works on the routing phase, in this case, could be Ribbon doing it. This library here only adds `ZuulFilter`s that runs before or after the routing.
