### ISSUE TITLE
Registering multiple rate limiters

### ISSUE THREAD

**Issue by jakubzloczewski** [marcosbarbero/spring-cloud-zuul-ratelimit#37]
My use case: I would like to do rate limiting in context of multiple keys. 

For example limit number of requests to 10 req/s for key = client+tenant+user but 1000 req/s for key = client+tenant.

Is it possible to accomplish this with current implementation?

**Comment by marcosbarbero** [comment]
Hello @jakubzloczewski in the current implementation you can set only one policy per route/service, it means you can't configure multiple keys.

Can you elaborate a little bit more? I'm curious how will you diff each case to use the proper key.

**Comment by jakubzloczewski** [comment]
It is very unclear how to do this diff so... never mind
