### ISSUE TITLE
How can I disable zuul rate limiter logging

### ISSUE THREAD

**Issue by sharunthomas** [marcosbarbero/spring-cloud-zuul-ratelimit#370]
**Describe the bug**
Is there any configuration stop the logging of rate limiter as it consumes a lot of server space

**Additional context**
I want to disable these kind of logs
2020-08-10 12:59:02.646 DEBUG 6812 --- [nio-8010-exec-9] o.s.web.servlet.DispatcherServlet : Successfully completed request

**Comment by marcosbarbero** [comment]
Hi @sharunthomas, it doesn't see to be a rate limiter log but a spring framework one. 
the `o.s.web.servet.` stands for `org.springframework.web.servlet.`, but answering your question you can disable it just relying on SpringBoot's logging configuration. [You can follow their official documentation to learn more about it].(https://docs.spring.io/spring-boot/docs/2.1.x/reference/html/boot-features-logging.html)

**Comment by sharunthomas** [comment]
Thank you for answering the question even if it wasn't related to the rate limiter.
