### ISSUE TITLE
Release 1.7.x branch

### ISSUE THREAD

**Issue by lchayoun** [marcosbarbero/spring-cloud-zuul-ratelimit#373]

**Comment by marcosbarbero** [comment]
@lchayoun did I miss something? :)

**Comment by lchayoun** [comment]
We merged the HEADER option to 1.7.x as well.
https://github.com/marcosbarbero/spring-cloud-zuul-ratelimit/commits/1.7.x

But I'm unable to release it.

**Comment by marcosbarbero** [comment]
I see! I'll take care of it later today

**Comment by lchayoun** [comment]
Reminder :)

**Comment by marcosbarbero** [comment]
Hey @lchayoun good morning.
I believe we have it [release now]( https://travis-ci.org/github/marcosbarbero/spring-cloud-zuul-ratelimit/builds/724592534#L6432).

```bash
NEW VERSION RELEASED
BUILD FINISHED
```

Could you please help me out to create a [release here on GitHub](https://github.com/marcosbarbero/spring-cloud-zuul-ratelimit/releases) I'm uncertain what's added with this one :D

**Comment by marcosbarbero** [comment]
@lchayoun 
FYI [v1.7.6.RELEASE](https://search.maven.org/artifact/com.marcosbarbero.cloud/spring-cloud-zuul-ratelimit/1.7.6.RELEASE/jar) is on maven central.
