### ISSUE TITLE
Does the project support zuul-core?

### ISSUE THREAD

**Issue by isaacchiang** [marcosbarbero/spring-cloud-zuul-ratelimit#376]
Greetings,
      We are building an API gateway in a project, instead of using spring-cloud-zuul, we use zuul-core for some reasons.
Recently we have a need of doing ratelimit and found this project. We were wondering if this project can be used with zuul-core? If not, does it have a version or module that directly support the zuul-core?

Thanks,

**Comment by marcosbarbero** [comment]
Hi @isaacchiang this project is built expecting some of the `spring-cloud-*` features to work. If you want to use it with the plain `zuul-core` you probably need to declare manually all the filters, and `@Bean`s from the [RateLimitAutoConfiguration](https://github.com/marcosbarbero/spring-cloud-zuul-ratelimit/blob/master/spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/RateLimitAutoConfiguration.java).

Unfortunately, there's not a version only for `zuul-core`.

**Comment by isaacchiang** [comment]
@marcosbarbero Got it, thank you!
