### ISSUE TITLE
ability to disable rate limiting basing on flag in request context

### ISSUE THREAD

**Issue by jakubzloczewski** [marcosbarbero/spring-cloud-zuul-ratelimit#38]
I would like to disable RateLimitPreFilter and RateLimitPostFilter on the fly. 

It would be great to modify implementation of shouldFilter method for filters. For example it will stop liming when "rateLimitDisabled" flag in request context is present and set true.

**Comment by lchayoun** [comment]
You can set the zuul.rateLimit.enabled=false, why do you need another flag?

**Comment by jakubzloczewski** [comment]
My need is to steer this flag in runtime - for example depending on request origin or user.

Do you suggest to wire RateLimitProperties been and use setEnabled method to modify flag? I'm not sure if it is safe to modify it as it is global state not in context of request.

**Comment by lchayoun** [comment]
It sounds to me that you need to create a filter that extends the RateLimitPreFilter and one that extends the RateLimitPostFilter
set zuul.rateLimit.enabled=false (or don't add it since it is the defualt) to disable the existing filters
than override the logic of the `shouldFilter` in each filter to match your dynamic logic

**Comment by jakubzloczewski** [comment]
Ok, thanks for advice. I will give a try.

**Comment by lchayoun** [comment]
@jakubzloczewski can we close this issue?

**Comment by fudali113** [comment]
@jakubzloczewski Do you think this will solve your problem? #41

**Comment by jakubzloczewski** [comment]
Yes, it works. Thanks!

**Comment by angshuman-agarwal** [comment]
> It sounds to me that you need to create a filter that extends the RateLimitPreFilter and one that extends the RateLimitPostFilter
> set zuul.rateLimit.enabled=false (or don't add it since it is the defualt) to disable the existing filters
> then override the logic of the `shouldFilter` in each filter to match your dynamic logic

I tried this suggestion in version `2.2.1.RELEASE`. But, I am getting error saying `Could not autowire. No beans of 'RateLimitProperties' type found` and same error for other classes being injected in ctor - `RateLimiter`, `RateLimitKeyGenerator` and `RateLimitUtils`. 

Any idea how to make that work please ?

**Comment by marcosbarbero** [comment]
@angshuman-agarwal this issue was closed almost 3 years ago and a lot has changed to the project structure during this time. I recommend you open a new issue detailing your use-case.

**Comment by angshuman-agarwal** [comment]
Sorry about that. I have raised it separately - https://github.com/marcosbarbero/spring-cloud-zuul-ratelimit/issues/396
