### ISSUE TITLE
APPLICATION FAILED TO START

### ISSUE THREAD

**Issue by fuhongtao** [marcosbarbero/spring-cloud-zuul-ratelimit#39]
use version 1.3.4.RELEASE
add property zuul.ratelimit.repository
Parameter 0 of method rateLimiterPreFilter in com.marcosbarbero.cloud.autoconfigure.zuul.ratelimit.RateLimitAutoConfiguration required a bean of type 'com.marcosbarbero.cloud.autoconfigure.zuul.ratelimit.config.RateLimiter' that could not be found.
	- Bean method 'consultRateLimiter' not loaded because @ConditionalOnProperty (zuul.ratelimit.repository=CONSUL) found different value in property 'repository'
	- Bean method 'inMemoryRateLimiter' not loaded because @ConditionalOnProperty (zuul.ratelimit.repository=IN_MEMORY) found different value in property 'repository'
	- Bean method 'redisRateLimiter' not loaded because @ConditionalOnProperty (zuul.ratelimit.repository=REDIS) found different value in property 'repository'
	- Bean method 'springDataRateLimiter' not loaded because @ConditionalOnProperty (zuul.ratelimit.repository=JPA) found different value in property 'repository'

**Comment by marcosbarbero** [comment]
What was the value you added to the property?

**Comment by fuhongtao** [comment]
i try  zuul.ratelimit.repository=IN_MEMORY  and   zuul.ratelimit.repository=REDIS . all two make mistakes

**Comment by marcosbarbero** [comment]
Do you have a sample project that I can check?

**Comment by marcosbarbero** [comment]
Ok, thank you

**Comment by fuhongtao** [comment]
Thank you for your support. For some reason, I may not send the item to you by mail. Please paste some files of my project for reference.
<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.5.6.RELEASE</version>
		<relativePath /> 
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
		<spring-cloud.version>Dalston.SR4</spring-cloud.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-eureka</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-zuul</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-cache</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-redis</artifactId>
		</dependency>
		<dependency>
			<groupId>com.maihaoche</groupId>
			<artifactId>spring-boot-starter-rocketmq</artifactId>
			<version>0.0.4</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-jdbc</artifactId>
		</dependency>
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-oauth2</artifactId>
		</dependency>
		<dependency>
			<groupId>com.marcosbarbero.cloud</groupId>
			<artifactId>spring-cloud-zuul-ratelimit</artifactId>
			<version>1.3.4.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

#zuul
#zuul.routes.api.stripPrefix=false /api/user/list -> /api/user/list
zuul.ribbon.eager-load.enabled= true

zuul.sensitiveHeaders=
zuul.add-host-headers=true

zuul.routes.local.path=/local/**
zuul.routes.local.url=forward:/local

zuul.routes.yd.path=/yd/**
zuul.routes.yd.url=http://tb.yidiantb.com
zuul.routes.yd.stripPrefix=false

zuul.ratelimit.enabled=true
#zuul.ratelimit.repository=IN_MEMORY 
zuul.ratelimit.policies.local.limit=3
zuul.ratelimit.policies.local.refresh-interval=60
zuul.ratelimit.policies.local.type=origin
zuul.ratelimit.policies.yd-admin.limit=30
zuul.ratelimit.policies.yd-admin.refresh-interval=60
zuul.ratelimit.policies.yd-admin.type=origin

**Comment by fuhongtao** [comment]
When I add the following code, everything is OK

	public static void main(String[] args) {
		// RateLimitAutoConfiguration a;
		SpringApplication.run(YdGatewayApplication.class, args);
	}
	  @Bean("rateLimiterRedisTemplate")
      public StringRedisTemplate redisTemplate(final RedisConnectionFactory connectionFactory) {
          return new StringRedisTemplate(connectionFactory);
      }

      @Bean
      public RateLimiter redisRateLimiter(@Qualifier("rateLimiterRedisTemplate") final RedisTemplate redisTemplate) {
          return new RedisRateLimiter(redisTemplate);
      }

**Comment by marcosbarbero** [comment]
I’ll play with your configuration and let you know once I have a solution

**Comment by marcosbarbero** [comment]
@fuhongtao can you take a look at [this sample](https://github.com/marcosbarbero/spring-cloud-zuul-ratelimit/tree/issue-39/spring-cloud-zuul-ratelimit-samples/playground)?

**Comment by fuhongtao** [comment]
i try the sample,it's not work.

**Comment by marcosbarbero** [comment]
I'll double check it
