### ISSUE TITLE
Support multiple policies

### ISSUE THREAD

**Issue by fudali113** [marcosbarbero/spring-cloud-zuul-ratelimit#40]
Currently only supports a policy, but in many cases, we need a variety of strategies for different current limit, so I would like to modify the code to support multiple policies, you think of this idea? I now have a fork branch that does this    [23mf:feat-support-policies](https://github.com/23mf/spring-cloud-zuul-ratelimit/tree/feat-support-policies)

**Comment by marcosbarbero** [comment]
Hello @fudali113, you can create a PR when you have your implementation done.
I'll do the code review and also will check if @lchayoun can help me on that.
