### ISSUE TITLE
Is it possible to use an In Memory Storage

### ISSUE THREAD

**Issue by borcas** [marcosbarbero/spring-cloud-zuul-ratelimit#404]
Hi everyone,
I would like to use your library, setting up redis or any other database would be overkill...
In https://blog.marcosbarbero.com/spring-cloud-netflix-zuul-rate-limit/ it is mentioned that an InMemory storage is supported, but I could not find anything in the code.
Could someone clarify this question?
Thanks and regards,
Boris

**Comment by marcosbarbero** [comment]
Hi @borcas, the blogpost is outdated and the `IN_MEMORY` implementation was dropped.
The issue #112 explains it further.
