### ISSUE TITLE
Should we manually implement the eviction for the infinispan cache ?

### ISSUE THREAD

**Issue by Arveti** [marcosbarbero/spring-cloud-zuul-ratelimit#405]
I am using spring-cloud-zuul-ratelimit with Bucket4j Infinispan implementation. My question is that will spring-cloud-zuul-ratelimit also evict the cache or even though expiration time / reset time pass, will the entry be in the cache? I don't want the inifinispan in-memory cache in the VM to grow exponentially for each originated request. Hence asking.
Awaiting reply.

**Comment by vladimir-bukhtoyarov** [comment]
Hello @Arveti 

Bucket4j does not manage expiration by itself. Instead, you need to configure a write-expire strategy for your cache.

**Comment by Arveti** [comment]
@vladimir-bukhtoyarov 
Got it. Just need help with my code. I wrote the following bean to remove the cache. 
`@Bean
    @Qualifier("RateLimit")
    public ReadWriteMap<String, GridBucketState> map() {
        DefaultCacheManager cacheManager = new DefaultCacheManager();
        cacheManager.defineConfiguration("rateLimit", new ConfigurationBuilder().clustering()
                .cacheMode(CacheMode.LOCAL).memory().size(2000).evictionType(EvictionType.COUNT).evictionStrategy(EvictionStrategy.REMOVE).build());
        AdvancedCache<String, GridBucketState> cache = cacheManager.<String, GridBucketState>getCache("rateLimit").getAdvancedCache();
        FunctionalMapImpl<String, GridBucketState> functionalMap = FunctionalMapImpl.create(cache);
        return ReadWriteMapImpl.create(functionalMap);
    }`

I couldn't find enough documentation and so asking this question. With the above code, Am I removing the whole cache with EvictionStrategy.REMOVE when 1000 COUNT is reached abruptly ? What happens to the requests whose quota is being tracked in origin based rate limiting ?

**Comment by vladimir-bukhtoyarov** [comment]
@Arveti which version of Infinispan do you use?

**Comment by Arveti** [comment]
@vladimir-bukhtoyarov I am using 9.4.0

**Comment by vladimir-bukhtoyarov** [comment]
```java
ConfigurationBuilder config = new ConfigurationBuilder();
config.expiration().maxIdle(60, TimeUnit.SECONDS); // bucket will be evicted after one minute of inactivity
```

**Comment by Arveti** [comment]
Great. Thank you so much. This helps a lot. Just one last question -
Is refill period same as zuul.ratelimit.default-policy-list[0].refresh-interval?
If not what is it ?

**Comment by marcosbarbero** [comment]
For some reason, I missed this issue yesterday.
Thanks @vladimir-bukhtoyarov for your support, I can't help but love OSS 😃

**Comment by Arveti** [comment]
@vladimir-bukhtoyarov / @marcosbarbero  Can you please confirm if policy refresh interval and bucket4j refill period both are same ? Would be really great. Thank you.

**Comment by marcosbarbero** [comment]
Hi @Arveti, yes the `refresh-internal` changes a bucket configuration on the fly to both are aligned. You can see it happening on this [line](https://github.com/marcosbarbero/spring-cloud-zuul-ratelimit/blob/master/spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/repository/bucket4j/AbstractBucket4jRateLimiter.java#L68)

**Comment by Arveti** [comment]
Thanks. Closing this.
