### ISSUE TITLE
A component required a bean named 'stringRedisTemplate' that could not be found

### ISSUE THREAD

**Issue by qxwei** [marcosbarbero/spring-cloud-zuul-ratelimit#414]
A component required a bean named 'stringRedisTemplate' that could not be found

**Comment by qxwei** [comment]
@gitter-badger I use   Spring Boot version 1.5.9  MUST use Spring Cloud Zuul RateLimit version 1.7.x.  ，I cannt update it

**Comment by qxwei** [comment]
@gitter-badger I use spring

**Comment by marcosbarbero** [comment]
Hi @qxwei, the general recommendation to update the latest version also goes for Spring Boot and Spring Cloud.
If you can share the full stack trace, I will try to help. 
Unfortunately, if it's a bug, it won't be fixed as the `1.x.x.RELEASE` line has hit its end of life.
