### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by farzad-g** [marcosbarbero/spring-cloud-zuul-ratelimit#423]
hi Marco 
I have this error how can you help me?
class file has wrong version 55.0, should be 52.0
![image](https://user-images.githubusercontent.com/52880839/111026196-4e171700-83fe-11eb-9e06-10683dcf3a10.png)

**Comment by marcosbarbero** [comment]
Hi @farzad-g it means you're running your project on Java 8, but this library is built on Java 11.
To fix it you must upgrade your JDK version to 11 or higher.
