### ISSUE TITLE
How to use JWT token user id as policy key to limit traffic to each user

### ISSUE THREAD

**Issue by pradeepkusingh** [marcosbarbero/spring-cloud-zuul-ratelimit#430]
**Describe the question**
How to use JWT token user id as policy key to limit traffic to each user

I have multiple user who are coming to my apigateway using JWT token and I would like to rate limit using JWT user id, how can I achieve that, any help would be highly appreciated.

**Comment by marcosbarbero** [comment]
Hi @pradeepkusingh. Unfortunately, as of now, this is not a supported feature. There's a draft similar to this one at #347, but it wasn't finished.

**Comment by pradeepkusingh** [comment]
Thanks @marcosbarbero , do we have any plan to wrap up the #347 ?

**Comment by marcosbarbero** [comment]
Unfortunately, I'm out of time to do that. If you feel like creating a PR I will be happy to review it

**Comment by kennyk** [comment]
Hi @pradeepkusingh, you should be able to do this by creating a [custom RateLimitKeyGenerator](https://github.com/marcosbarbero/spring-cloud-zuul-ratelimit#key-generator), where the key is the JWT user id. Of course you will need to parse and validate your JWTs inside the generator implementation - but this approach should work.
