### ISSUE TITLE
2.4.2.RELEASE not supposed JDK 8  ?

### ISSUE THREAD

**Issue by sunyl-git** [marcosbarbero/spring-cloud-zuul-ratelimit#445]
**Describe the question**
  ERROR MSG , compile error   bad class file:  class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.

**Additional context**

 Please don't give up support for jdk8.   jdk8 project  introduces 2.4.2.RELEASE version, it will compile failure

**Comment by marcosbarbero** [comment]
Hi @sunyl-git, apologies for the long delay.
Can't you migrate your project to use java 11?

**Comment by sunyl-git** [comment]
Thank you for your suggestion，I will upgrad  to jdk11 in next time.   I recompiled spring-cloud-zuul-ratelimit  project with jdk8 to fix  'error bad class'

**Comment by marcosbarbero** [comment]
Thank you. If you have any questions or comments please don't hesitate to contact.
