### ISSUE TITLE
Storage service downgrade

### ISSUE THREAD

**Issue by fudali113** [marcosbarbero/spring-cloud-zuul-ratelimit#45]
If the storage service fails, let the user decide in the configuration file whether or not to pass the check.

such as : 
 my repo is redis, but my redis server is done, RateLimitFilter Should it pass?
@marcosbarbero

**Comment by lchayoun** [comment]
@fudali113 I agree, all the repository should handle failures of the backend
@marcosbarbero WDYT?

**Comment by marcosbarbero** [comment]
That actually is a a great idea.

**Comment by marcosbarbero** [comment]
@fudali113 this issue is closed by [v1.4.0.RELEASE](https://github.com/marcosbarbero/spring-cloud-zuul-ratelimit/releases/tag/v1.4.0.RELEASE).

If you find any issue in the future let us know.

kudos @lchayoun
