### ISSUE TITLE
Bucket4J with remote Ignite

### ISSUE THREAD

**Issue by BiatBang** [marcosbarbero/spring-cloud-zuul-ratelimit#451]
I wonder if it's possible to connect to Ignite cache in a remote deployment. 

I have a gateway replica set and I would like them to talk to one Ignite server. I tried to reconfigure the ignite server but seems it's still using in-memory cache. Do you know how can I make this out? Thanks a lot.

**Comment by marcosbarbero** [comment]
Hi @BiatBang, does this page help you to connect to a remote server? https://ignite.apache.org/docs/latest/extensions-and-integrations/spring/spring-boot

**Comment by BiatBang** [comment]
No, this doesn't provide a way to create an ignite instance. However this article is helpful. https://egkatzioura.com/2020/04/09/apache-ignite-and-spring-on-your-kubernetes-cluster-part-1-spring-boot-application/ . Anyone's facing problem like this can read this one. I'll close this issue.
