### ISSUE TITLE
Rate Limit for List of Users

### ISSUE THREAD

**Issue by CasperOm** [marcosbarbero/spring-cloud-zuul-ratelimit#454]
Hi @marcosbarbero ,

It will be good enhancement if we can add the functionality to add list user OR origin under type. Please let me know if any other way is available for this type of requirement.

Thanks

**Comment by marcosbarbero** [comment]
Thanks for the suggestion @CasperOm.
What do you think @lchayoun, instead of a single value for the types we start accepting a comma-delimited list?

**Comment by lchayoun** [comment]
@marcosbarbero 
I think we can change it to a list input, and support the single string on the same attribute
