### ISSUE TITLE
JDK 8 compatibility

### ISSUE THREAD

**Issue by adamalexandru4** [marcosbarbero/spring-cloud-zuul-ratelimit#457]
I saw that version 2.4.2.RELEASE is migrated to JDK 11 but a lot of projects don't want to do this too. 
Would be great if this project could still be compatible with JDK 8. 

Reason: I need the new functionality with HTTP Header which is available in 2.4.2, but I can only use 2.4.1 due to JDK 8 setup.

**Comment by marcosbarbero** [comment]
Thanks for your feedback @adamalexandru4, I'll try to work on this asap.

**Comment by angshuman-agarwal** [comment]
Is there a rough ETA for this version please ? I need the JDK 8 compatible version as well due to similar requirements.

**Comment by marcosbarbero** [comment]
I'm sorry for the delay, most of the time invested in this project is my personal time, and I do not have a lot of time to fix this issue.  As it's an open-source project, I would gladly review accept a merge request fixing this issue.

Releasing a new version wouldn't take that long.
