### ISSUE TITLE
URL Pattern key

### ISSUE THREAD

**Issue by adamalexandru4** [marcosbarbero/spring-cloud-zuul-ratelimit#476]
Using URL_PATTERN type should generate a key as it follows:

`key-prefix:routeId:URL:.....`
**NOT**
`key-prefix:routeId:MATCHER:....`

Why would you use matcher instead of the real URL used with PathVariables or RequestParams. It's not a good solution.
I can make a pull request to solve this issue.

**Comment by marcosbarbero** [comment]
It's an open-source project. Pull Requests are welcome.
