### ISSUE TITLE
General Question for better understanding

### ISSUE THREAD

**Issue by akshaydk-buku** [marcosbarbero/spring-cloud-zuul-ratelimit#506]
1. What kind of rate limiting algorithm is being leveraged here? (Ex. Token Bucket, Sliding Window etc)
2. If we go with Redis as our data storage, does it come with the feature of distributed locking?
3. If not, how do we enable the same since persisting the rate limit headers are not within our reach?
4. Is client side rate limiting also possible?
5. If let's say a particular IP/host has to be blacklisted, is there a way we could just enable it on the fly and avoid manual reboot by reconfiguring rate limit properties of Zuul api gateway service?

Best Regards,
Akshay

**Comment by akshaydk-buku** [comment]
@marcosbarbero any update on this please?

**Comment by akshaydk-buku** [comment]
@lchayoun please review

**Comment by marcosbarbero** [comment]
I'm sorry for the delay, I'm currently on a road trip and have very limited internet connection.

I will get back to you early next week.

**Comment by akshaydk-buku** [comment]
Sure. have few more questions around this
have created a separate issue for the same.
https://github.com/marcosbarbero/spring-cloud-zuul-ratelimit/issues/510
Please have a look at the above

**Comment by akshaydk-buku** [comment]
@marcosbarbero @lchayoun any update on this?

**Comment by marcosbarbero** [comment]
Hi @akshaydk-buku sorry for the long time to get back to you, I'll try to answer your questions here:

> 1. What kind of rate-limiting algorithm is being leveraged here? (Ex. Token Bucket, Sliding Window etc)

It uses [Token Bucket](https://github.com/vladimir-bukhtoyarov/bucket4j).

> 2. If we go with Redis as our data storage, does it come with the feature of distributed locking?

It depends entirely on how you configure your Redis cluster.

> 4. Is client-side rate limiting also possible?

This library only does server-side rate limiting.

> 5. If let's say a particular IP/host has to be blacklisted, is there a way we could just enable it on the fly and avoid manual reboot by reconfiguring rate limit properties of Zuul api gateway service?

This library relies on [Spring Boot's Autoconfiguration](https://spring.io/guides/gs/centralized-configuration/) and its ability to refresh configuration on the fly.

**Comment by akshaydk-buku** [comment]
Hi @marcosbarbero Thanks for you reply.

However, we're not using Spring Cloud Config Server and rather are fetching configuration properties from AWS SSM.

**Comment by marcosbarbero** [comment]
As soon as you use a refresh strategy supported by Spring Boot, it will work using this project as well.
