### ISSUE TITLE
Implement token-bucket algorithm

### ISSUE THREAD

**Issue by marcosbarbero** [marcosbarbero/spring-cloud-zuul-ratelimit#55]
@lchayoun I'm thinking about to change our main implementation to use a `token-bucket` instead.
Here's a link to take a look https://github.com/bbeck/token-bucket.

WDYT?

**Comment by lchayoun** [comment]
I think it is a good direction, not sure about this implementation.
[bucket4j](https://github.com/vladimir-bukhtoyarov/bucket4j) has good integration with spring and is out there for quite a while

**Comment by marcosbarbero** [comment]
Good to know.
I’ll take a look ASAP.

**Comment by marcosbarbero** [comment]
@lchayoun did you see those [examples](https://github.com/MarcGiffing/bucket4j-spring-boot-starter-examples)?

**Comment by lchayoun** [comment]
Saw them, I think the main issue is the configuration required because it is not zuul specific.
I think we should support it as backend, we'll gain the support for all the backends supported by `bucket4j`

**Comment by marcosbarbero** [comment]
Don't you think it would be better to entirely move the ratelimit algorithm to a `bucket` based one? Doesn't necessarily needs to be `bucket4j`.

**Comment by lchayoun** [comment]
Well, since buckets doesn't work natively with time limitation, the filters are still required.
Also redis is a very good backend and I think it need to remain.
Adding bucket4j as `RateLimiter` implementation will give us the logic of it with the backends supported without losing any capability.

**Comment by marcosbarbero** [comment]
Actually that's the main idea, I'm not planning to remove any supported backend just to move the logic towards a bucked based algorithm.

**Comment by lchayoun** [comment]
not sure I understood, maybe we are saying the same.
I think that it should be added first as another backend without modifying the existing ones and later on change merge them.

**Comment by marcosbarbero** [comment]
I think we are actually saying the same thing :D
