### ISSUE TITLE
Add Spring Cloud Finchley Support

### ISSUE THREAD

**Issue by dengxue0** [marcosbarbero/spring-cloud-zuul-ratelimit#57]

**Comment by marcosbarbero** [comment]
Thanks for the collaboration @dengxue0 I'll try to make it work by the end of this week.

**Comment by lchayoun** [comment]
Since this project depends on [Spring Cloud](http://projects.spring.io/spring-cloud/) it is worth waiting for the first release

**Comment by marcosbarbero** [comment]
As [Spring Cloud Finchley](https://spring.io/blog/2018/06/19/spring-cloud-finchley-release-is-available) was released today, we should start to work on this support.
