### ISSUE TITLE
Automate release in travis ci when merged to master

### ISSUE THREAD

**Issue by marcosbarbero** [marcosbarbero/spring-cloud-zuul-ratelimit#59]
Whenever it's merged to master travis ci needs to be able to release a new version to maven central.

**Comment by lchayoun** [comment]
I think that it should only happend if the merge message contains a key word "Release Version" or somthing similar

**Comment by marcosbarbero** [comment]
We can set a pattern for that, my first thought was to always work on develop and then merge to master meaning it is a release version, however, I like more your idea where we set some pattern for the versioning.
