### ISSUE TITLE
about use custom redis

### ISSUE THREAD

**Issue by dchack** [marcosbarbero/spring-cloud-zuul-ratelimit#68]
hi,I have tow question, if you have time, please give me some opinions, thank you.
First,i want use my redis config, so i create this class:
```java

@Component
@Configuration
public class RedisRateLimiterConfiguration {

    @Autowired
    RedisTemplate redisTemplate;

    @Bean
    public RateLimiter redisRateLimiter(RateLimiterErrorHandler rateLimiterErrorHandler) {
        return new RedisRateLimiter(rateLimiterErrorHandler, redisTemplate);
    }
}
```
Because there is no wiki to know how to do, so my question is this is right or perfect way?

Second,`RateLimitPreFilter`and `RateLimitPostFilter` have hard coding `filterOrder`, how can i change it.

**Comment by marcosbarbero** [comment]
Hi, @dchack thanks for your questions.

Currently, you can't override the `filterOrder`, it's not something provided by `spring-cloud-netflix-zuul`.
Also, there's no way to override `RedisTemplate`, however, may I ask why do you need to use your own `RedisTemplate`?

**Comment by dchack** [comment]
@marcosbarbero For example, one project have tow redis to connect.

**Comment by lchayoun** [comment]
Not sure I fully understood the issue.

Adding the following code will be enough in order to provide custom redisTemplate:
```java
@Primary
@Bean("rateLimiterRedisTemplate")
public StringRedisTemplate redisTemplate() {
    return //Custom Redis template;
}
```

**Comment by dchack** [comment]
@lchayoun Yes,you are right, i mean that you can create a wiki to explain it, as some new starter don't what way is recommended.
in my case, my project not have a `StringRedisTemplate `,so i use `redisTemplate` directly.
