### ISSUE TITLE
about ZuulRuntimeException

### ISSUE THREAD

**Issue by dchack** [marcosbarbero/spring-cloud-zuul-ratelimit#69]
hi, in the code of `RateLimitPreFilter`,we will throw a Exception:`ZuulRuntimeException` to show Too Many Requests.
But as a gateway, I must ensure no exception throw to clients.
so I create a `Error Filter` as a adapter for the exceptions. I think if throw a custom Exception,it is easy use `instanceof` to distinguish.
For example, when there is a `Too Many Requests Exception`, I want to return client a custom string message.

**Comment by lchayoun** [comment]
I think it is a always a good idea to throw specific exception.
