### ISSUE TITLE
How to use this situation

### ISSUE THREAD

**Issue by kklt1990** [marcosbarbero/spring-cloud-zuul-ratelimit#71]
An application with @EnableZuulProxy could act as a standalone server if you set a default route ("/"), for example zuul.route.home: / would route all traffic (i.e. "/**") to the "home" service.

**Comment by lchayoun** [comment]
You can add multiple policies and specify the relevant url for the policy.
If you want it to apply for all services you can use the `zuul.ratelimit.default-policy-list` property

**Comment by kklt1990** [comment]
I use the zuul.ratelimit.default-policy-list property for all services. but it not work.
This config like this.
![image](https://user-images.githubusercontent.com/25313758/39562524-b16bd546-4ede-11e8-8d30-7985721e3a08.png)
This "home" service which is contain zuul and act as a standalone server.

**Comment by kklt1990** [comment]
when I request 51 times per minutes it not response 429 http status.

**Comment by lchayoun** [comment]
when you receive the response a "X-RateLimit-Remaining-" postfixed header is returned with the remaining allowed requests.
Can you check what is the header value?

**Comment by kklt1990** [comment]
![image](https://user-images.githubusercontent.com/25313758/39574792-f208c452-4f0a-11e8-9571-029d817c8b41.png)
I don't known why it not work.

**Comment by marcosbarbero** [comment]
Closed due to inactivity.
