### ISSUE TITLE
how do you configure different current limiting strategies for some URL in a service?

### ISSUE THREAD

**Issue by zhangjianbinJAVA** [marcosbarbero/spring-cloud-zuul-ratelimit#75]
Hello, how do you configure different current limiting strategies for some URL in a service?

For example:

URL /test1 limit call number 10 in service A

URL /test2 limit call number 2 in service A

**Comment by marcosbarbero** [comment]
Did you check #64 ?

**Comment by marcosbarbero** [comment]
Closed due to inactivity.
