### ISSUE TITLE
`policy(route, request)` called 4 times during handling one request

### ISSUE THREAD

**Issue by Aloren** [marcosbarbero/spring-cloud-zuul-ratelimit#77]
I was looking into filters and found that `policy(route, request)` is called 4 times during routing of the one request. Two times it is called in each `shouldFilter` and another 2 times in each `run` method of  pre and post filters.
I think that this value could be computed on first `shouldFilter` and put into `RequestContext`.

The same applies to `route(HttpServletRequest request)` method.

WDYT?

**Comment by marcosbarbero** [comment]
That's a good improvement.

**Comment by lchayoun** [comment]
For the shouldFilter and run I agree.
But the postFilter shouldFilter function should run it again in order to allow other filters to intervene.

**Comment by Aloren** [comment]
@lchayoun hm.. i didn't understand. why do we need to call `policy(route(request), request)` in post filter and can't use the value computed in prefilter?

**Comment by lchayoun** [comment]
The request can be changed by other filters during the request.
Computing and storing it will make the post filter ignore the change.

**Comment by Aloren** [comment]
good point. do you remember is there a test for such scenario?

**Comment by lchayoun** [comment]
I don't think so since the current tests are not adding custom filters to do so.

**Comment by marcosbarbero** [comment]
@Aloren are you willing to work on this one?

**Comment by Aloren** [comment]
@marcosbarbero sorry guys i'm currently short on time, hope to have some time on weekends. if you want to do it ASAP then of course you can start implementing it yourself.

**Comment by marcosbarbero** [comment]
Don’t worry, take your time! I just asked because in case you were not interested in implementing it yourself we should assign it internally.
