### ISSUE TITLE
Is that possible to control rate limit dynamically?

### ISSUE THREAD

**Issue by willswl** [marcosbarbero/spring-cloud-zuul-ratelimit#79]
In my case, service#1 and service#2 are sharing a same request pool (to access a thirdparty service). The access rate of service#2 is very unstable, usually it's free, but sometimes many connections may come in suddenly and it will become very busy

What I want to implemented is: limit service#1 to 5 qps as a basic,  limit service#2 to 10 qps as a basic, when service#1 reaches its limit, I want to check if service#2 is busy or not , if service#2 is not very busy, I will let service#1 steal 1 quota from service#2 for this perticular access.

**Comment by marcosbarbero** [comment]
I don't believe that's possible to achieve in the current implementation

**Comment by willswl** [comment]
I worked around this problem, but seems it's hard to integrate my solution to the current zuul-ratelimit inplementation.

What I did :  created a rate limit checker in zuul filter by using ["es.moki.ratelimitj"](https://github.com/mokies/ratelimitj), and defined a policy as below: 
    ratelimit:
        repository: Redis
        policy-list:
          - service-name: service#1 
            limit: 5
            refresh-interval: 1
            sharable: false  # can not be stolen 
          - service-name: service#2
            limit: 6           
            refresh-interval: 1
            sharable: true # can not be stolen 
          - service-name: service#2
            limit: 4
            refresh-interval: 1
            sharable: true # can be stolen

**Comment by willswl** [comment]
It's totally a new implementation, but I did refer to your solution to define my policy and the limiting process. I would try to implement that by extending zuul-ratelimit after my busy project work finished.

My solution is simple:  I leverage ratelimitj as a standalone limiter, I defined all the three limiters with ratelimitj. When a request comes in, firstly I checked the service name, and found the corresponding limiter that is not sharable. if the limiter is full, I will then look for another limiter that is sharable.

**Comment by lchayoun** [comment]
well, making two policies use the same allocation (limit / quota) should be easy enough by adding a property to the policy `name` and in the other policies add a property that specify they consume the other policy quota.
But that not exactly what described here.
Making one policy overflow to another one as described will be harder but it also doable.
We can add a property to specify the overflow policy and on failure to consume try to take it from the other policy.

I think this request is a combination of those two capabilities

**Comment by dchack** [comment]
I think if you overwrite filter(RateLimitPostFilter and 
) , and do some thing for your customer implementation will control rate limit dynamically.
