### ISSUE TITLE
Multiple policy for one service

### ISSUE THREAD

**Issue by prasetyasetiawantiketcom** [marcosbarbero/spring-cloud-zuul-ratelimit#83]
Hi another question is it possible to have multiple policy for one service tried by seems cant do it correctly
Lets say we wanted to have within 1 minute max 10 request, but within 1 hour max 100 request

**Comment by marcosbarbero** [comment]
Hello @prasetyasetiawantiketcom you can configure multiple policies per service using the `policy-list` property, you can check an example in the `README` file.

**Comment by marcosbarbero** [comment]
Closed due to inactivity.
