### ISSUE TITLE
Add support for consul backend

### ISSUE THREAD

**Issue by lchayoun** [marcosbarbero/spring-cloud-zuul-ratelimit#9]
Consul support key value data store.
Is there a possibility to add consul support?

**Comment by marcosbarbero** [comment]
@lchayoun thanks for the question. I'll take a look how consul works and I keep you updated.

**Comment by lchayoun** [comment]
@marcosbarbero added an example of the implementation on #10

**Comment by marcosbarbero** [comment]
thanks so much, I'll take a look shortly :)

**Comment by marcosbarbero** [comment]
@lchayoun I just pushed an initial implementation for consul based on your PR.
I'm still working on integration tests, somewhere further in this week I'll probably release a new version with consul support.

**Comment by lchayoun** [comment]
@marcosbarbero looking good, I would suggest making the inMemory implementation as one of the strategies and condition on that property instead of the corrent condition.
the inMemory implementation can be good even for production usages

**Comment by marcosbarbero** [comment]
My idea is to make `inMemory` the default option, in case no strategy is defined it will be using `inMemory` implementation. WDYT?

**Comment by lchayoun** [comment]
`inMemory` as default sounds good!

I guess that `repository` can describe it well.

**Comment by marcosbarbero** [comment]
Great, I just created a new branch and applied the property name change.
I'll try to push this new version on maven central until next coming Thursday.

**Comment by marcosbarbero** [comment]
@lchayoun I just deployed [v1.2.0.RELEASE](https://github.com/marcosbarbero/spring-cloud-zuul-ratelimit/releases/tag/v1.2.0.RELEASE) to maven central.

**Comment by lchayoun** [comment]
@marcosbarbero Thanks!!

**Comment by marcosbarbero** [comment]
@lchayoun thank you for all the support! 
If you have any further improvement ideas don't hesitate to reach me.
