### ISSUE TITLE
2.0.1.release problem, I set the limit to 4, Actually only let the visit twice, the third time will throw a  limit exception

### ISSUE THREAD

**Issue by lixinglin0213** [marcosbarbero/spring-cloud-zuul-ratelimit#92]
As the title says , The simplest function is wrong

this is my applicatin.yml

```java
 ratelimit:
    key-prefix:
    enabled: true
    repository: IN_MEMORY
    behind-proxy: true
    default-policy-list:
      - limit: 4
        quota: 2000
        refresh-interval: 30
        type:
          - url=/api/get/256Byte
```
But only allow me to visit the url (/api/get/256Byte) twice

**Comment by marcosbarbero** [comment]
Hello @lixinglin0213, how are you testing it?

**Comment by lixinglin0213** [comment]
@marcosbarbero 
Yes, I think it should be a problem with 2.0.1.release

**Comment by lixinglin0213** [comment]
Hello @marcosbarbero 
I use zuul1 in combination with ratelimit and then access the gateway to forward to /api/get/256Byte,
I set the limit number to 4, but only allow me to request twice. This problem is no problem at 2.0.0.release

**Comment by lchayoun** [comment]
Hi @lixinglin0213 
Can you please attach the response headers of the two requests so we could understand the issue?

**Comment by lixinglin0213** [comment]
Hi @lchayoun  This is a simple request for gateway forwarding.a total of two requests, the information is as follows

fisrt request:
`Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Content-Type: text/html;charset=UTF-8
Date: Thu, 12 Jul 2018 23:58:11 GMT
Expires: 0
Pragma: no-cache
Transfer-Encoding: chunked
X-Application-Context: msp-gateway:dev:8888
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-RateLimit-Limit-_tap_api_get_256Kb_api_get_256Kb: 4
X-RateLimit-Quota-_tap_api_get_256Kb_api_get_256Kb: 2000
X-RateLimit-Remaining-_tap_api_get_256Kb_api_get_256Kb: 2
X-RateLimit-Remaining-Quota-_tap_api_get_256Kb_api_get_256Kb: 2000
X-RateLimit-Reset-_tap_api_get_256Kb_api_get_256Kb: 30000
X-XSS-Protection: 1; mode=block`

second request:
`Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Content-Type: text/html;charset=UTF-8
Date: Thu, 12 Jul 2018 23:59:09 GMT
Expires: 0
Pragma: no-cache
Transfer-Encoding: chunked
X-Application-Context: msp-gateway:dev:8888
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-RateLimit-Limit-_tap_api_get_256Kb_api_get_256Kb: 4
X-RateLimit-Quota-_tap_api_get_256Kb_api_get_256Kb: 2000
X-RateLimit-Remaining-_tap_api_get_256Kb_api_get_256Kb: 0
X-RateLimit-Remaining-Quota-_tap_api_get_256Kb_api_get_256Kb: 1998
X-RateLimit-Reset-_tap_api_get_256Kb_api_get_256Kb: 24603
X-XSS-Protection: 1; mode=block`
