### ISSUE TITLE
Can I dynamically add or remove the current limit configuration for a specific interface?

### ISSUE THREAD

**Issue by lixinglin0213** [marcosbarbero/spring-cloud-zuul-ratelimit#93]
Can the traffic limiting configuration dynamically add or remove some traffic limiting policies without shutting down the gateway service?

**Comment by lchayoun** [comment]
Hi @lixinglin0213 , a reload of the gateway should be enough to change configuration since it is on the refresh scope

**Comment by lixinglin0213** [comment]
@lchayoun 
Found a solution, spring cloud config has implemented this feature,thanks
