### ISSUE TITLE
Synchronized consume method in AbstractCacheRateLimiter impact performance

### ISSUE THREAD

**Issue by addozhang** [marcosbarbero/spring-cloud-zuul-ratelimit#96]
Currently we are using 1.7.2 which is similar with `AbstractCacheRateLimiter ` in latest version. The repository we use is redis. 

We did performance test. With 1.7.2, the TPS is `600+`. After remove `synchronized `, it is up to `2000+`. 

In `AbstractCacheRateLimiter`, it has a `synchronized` method. In redis implementation, there is no object shared among threads. This method is invoked by each incoming request.

**Comment by lchayoun** [comment]
@addozhang 
I think that the `synchronized` method is important otherwise we might miss consumptions.

**Comment by addozhang** [comment]
But in `RedisRateLimiter`, both `RateLimiterErrorHandler` and `RedisTemplate` are thread-safe. It is not necessary to use `synchronized`.

**Comment by lchayoun** [comment]
Hi, @addozhang we recently changed the code in #108 and it should has better performance.
Can you test it?

**Comment by marcosbarbero** [comment]
Closing due inactivity

**Comment by Fangfeikun** [comment]
@lchayoun Why you think remove` synchronized` method, it might miss consumptions.

**Comment by addozhang** [comment]
@Fangfeikun Let me answer it. `synchronized` is usually used in race condition. ZuulFilter should be stateless object among requests. `RateLimiter` object used in `RateLimitPreFilter` should be stateless object too. Otherwise, all requests in this filter will wait for the monitor of `RateLimiter`.

**Comment by addozhang** [comment]
@lchayoun Sorry for late reply.
I am confused. What is protected by `synchronized`?  In RedisRateLimiter, both RateLimiterErrorHandler and RedisTemplate are thread-safe. There are no objects cannot be shared among threads.

**Comment by taxus1** [comment]
@addozhang How do you solve this? remove synchronized key word has any problem?

**Comment by addozhang** [comment]
@taxus1 yes, by removing `synchronized` and no any other problem found.

**Comment by taxus1** [comment]
@addozhang thanks
